import Foundation

// AUTO-GENERATED by tools/generate_levels.py — do not edit by hand.
// Re-run the generator to update levels.

enum Dir {
    case across
    case down
}

struct PlacedWord {
    let word: String
    let row: Int
    let col: Int
    let dir: Dir
}

struct Cell: Hashable {
    let row: Int
    let col: Int
}

struct Level {
    static let totalLevels = 100

    let rows: Int
    let cols: Int
    let letters: [Character]
    let words: [PlacedWord]

    var answersSet: Set<String> { Set(words.map { $0.word }) }

    var usedCells: Set<Cell> {
        var used = Set<Cell>()
        for pw in words {
            for i in 0..<pw.word.count {
                let cell: Cell
                switch pw.dir {
                case .across: cell = Cell(row: pw.row, col: pw.col + i)
                case .down:   cell = Cell(row: pw.row + i, col: pw.col)
                }
                used.insert(cell)
            }
        }
        return used
    }

    func solutionLetter(row: Int, col: Int) -> Character? {
        for pw in words {
            for (i, ch) in pw.word.enumerated() {
                let r: Int, c: Int
                switch pw.dir {
                case .across: r = pw.row; c = pw.col + i
                case .down:   r = pw.row + i; c = pw.col
                }
                if r == row && c == col { return ch }
            }
        }
        return nil
    }

    var bonusWords: [String] { LEVEL_BONUS[String(letters)] ?? [] }

    static func get(_ levelNum: Int) -> Level {
        let idx = max(0, min(levelNum - 1, LEVELS.count - 1))
        return LEVELS[idx]
    }
}

private let LEVELS: [Level] = [
    Level(rows: 5, cols: 5, letters: ["C", "A", "T", "S"],
          words: [PlacedWord(word: "CAST", row: 1, col: 0, dir: .across), PlacedWord(word: "CAT", row: 1, col: 0, dir: .down), PlacedWord(word: "SAT", row: 1, col: 2, dir: .down)]),
    Level(rows: 6, cols: 6, letters: ["S", "P", "I", "N", "E"],
          words: [PlacedWord(word: "SPINE", row: 1, col: 0, dir: .across), PlacedWord(word: "SIN", row: 1, col: 0, dir: .down), PlacedWord(word: "NIP", row: 1, col: 3, dir: .down), PlacedWord(word: "PEN", row: 3, col: 3, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["H", "A", "S", "T", "E"],
          words: [PlacedWord(word: "HASTE", row: 1, col: 0, dir: .across), PlacedWord(word: "HATE", row: 1, col: 0, dir: .down), PlacedWord(word: "SEAT", row: 1, col: 2, dir: .down), PlacedWord(word: "EAT", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["W", "A", "R", "M", "S"],
          words: [PlacedWord(word: "SWARM", row: 1, col: 0, dir: .across), PlacedWord(word: "SAW", row: 1, col: 0, dir: .down), PlacedWord(word: "RAM", row: 1, col: 3, dir: .down), PlacedWord(word: "WARM", row: 3, col: 0, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["C", "A", "R", "E", "S"],
          words: [PlacedWord(word: "CARES", row: 1, col: 0, dir: .across), PlacedWord(word: "CARE", row: 1, col: 0, dir: .down), PlacedWord(word: "SEAR", row: 1, col: 4, dir: .down), PlacedWord(word: "ERA", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["G", "R", "I", "N", "D", "S"],
          words: [PlacedWord(word: "GRINS", row: 1, col: 0, dir: .across), PlacedWord(word: "GIN", row: 1, col: 0, dir: .down), PlacedWord(word: "SIR", row: 1, col: 4, dir: .down), PlacedWord(word: "RID", row: 3, col: 4, dir: .across), PlacedWord(word: "DIG", row: 3, col: 6, dir: .down)]),
    Level(rows: 8, cols: 8, letters: ["P", "L", "A", "N", "E", "T", "S"],
          words: [PlacedWord(word: "PLANETS", row: 1, col: 0, dir: .across), PlacedWord(word: "PETAL", row: 1, col: 0, dir: .down), PlacedWord(word: "NETS", row: 1, col: 3, dir: .down), PlacedWord(word: "SLANT", row: 1, col: 6, dir: .down), PlacedWord(word: "ANTS", row: 4, col: 0, dir: .across)]),
    Level(rows: 8, cols: 8, letters: ["C", "R", "A", "N", "E", "S", "D"],
          words: [PlacedWord(word: "CRANES", row: 1, col: 0, dir: .across), PlacedWord(word: "CARED", row: 1, col: 0, dir: .down), PlacedWord(word: "NEARS", row: 1, col: 3, dir: .down), PlacedWord(word: "SANE", row: 1, col: 5, dir: .down), PlacedWord(word: "DENS", row: 5, col: 0, dir: .across), PlacedWord(word: "END", row: 5, col: 1, dir: .down)]),
    Level(rows: 8, cols: 8, letters: ["S", "T", "O", "R", "E", "D"],
          words: [PlacedWord(word: "STORED", row: 1, col: 0, dir: .across), PlacedWord(word: "SORT", row: 1, col: 0, dir: .down), PlacedWord(word: "REST", row: 1, col: 3, dir: .down), PlacedWord(word: "DOSE", row: 1, col: 5, dir: .down), PlacedWord(word: "ROES", row: 3, col: 0, dir: .across)]),
    Level(rows: 9, cols: 9, letters: ["T", "R", "A", "I", "N", "S", "E"],
          words: [PlacedWord(word: "TRAINS", row: 1, col: 0, dir: .across), PlacedWord(word: "TEARS", row: 1, col: 0, dir: .down), PlacedWord(word: "INSET", row: 1, col: 3, dir: .down), PlacedWord(word: "SIREN", row: 1, col: 5, dir: .down), PlacedWord(word: "ANTS", row: 3, col: 0, dir: .across), PlacedWord(word: "SENT", row: 5, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["G", "R", "A", "C", "E"],
          words: [PlacedWord(word: "RAGE", row: 2, col: 0, dir: .across), PlacedWord(word: "GRACE", row: 1, col: 0, dir: .down), PlacedWord(word: "CARE", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["D", "R", "E", "A", "M"],
          words: [PlacedWord(word: "RAMED", row: 2, col: 0, dir: .across), PlacedWord(word: "DREAM", row: 1, col: 0, dir: .down), PlacedWord(word: "ARMED", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["S", "T", "O", "R", "M"],
          words: [PlacedWord(word: "MOST", row: 1, col: 0, dir: .across), PlacedWord(word: "STORM", row: 1, col: 2, dir: .down), PlacedWord(word: "SORT", row: 3, col: 1, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["F", "L", "A", "M", "E"],
          words: [PlacedWord(word: "MEAL", row: 2, col: 0, dir: .across), PlacedWord(word: "FLAME", row: 1, col: 3, dir: .down), PlacedWord(word: "MALE", row: 2, col: 0, dir: .down)]),
    Level(rows: 6, cols: 5, letters: ["L", "I", "G", "H", "T"],
          words: [PlacedWord(word: "LIGHT", row: 2, col: 0, dir: .across), PlacedWord(word: "TIL", row: 1, col: 1, dir: .down), PlacedWord(word: "HIT", row: 2, col: 3, dir: .down)]),
    Level(rows: 7, cols: 4, letters: ["S", "T", "O", "N", "E"],
          words: [PlacedWord(word: "NEST", row: 1, col: 0, dir: .across), PlacedWord(word: "STONE", row: 1, col: 2, dir: .down), PlacedWord(word: "NOSE", row: 1, col: 0, dir: .down)]),
    Level(rows: 7, cols: 4, letters: ["W", "A", "T", "E", "R"],
          words: [PlacedWord(word: "WEAR", row: 1, col: 0, dir: .across), PlacedWord(word: "WATER", row: 1, col: 0, dir: .down), PlacedWord(word: "TEAR", row: 3, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["O", "C", "E", "A", "N"],
          words: [PlacedWord(word: "ACNE", row: 2, col: 0, dir: .across), PlacedWord(word: "OCEAN", row: 1, col: 1, dir: .down), PlacedWord(word: "ONCE", row: 5, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["P", "E", "A", "C", "E"],
          words: [PlacedWord(word: "PACE", row: 1, col: 0, dir: .across), PlacedWord(word: "PEACE", row: 1, col: 0, dir: .down), PlacedWord(word: "CAPE", row: 1, col: 2, dir: .down)]),
    Level(rows: 7, cols: 5, letters: ["S", "P", "A", "C", "E"],
          words: [PlacedWord(word: "CAPES", row: 2, col: 0, dir: .across), PlacedWord(word: "SPACE", row: 1, col: 2, dir: .down), PlacedWord(word: "CASE", row: 2, col: 0, dir: .down)]),
    Level(rows: 6, cols: 5, letters: ["S", "H", "I", "N", "E"],
          words: [PlacedWord(word: "SHINE", row: 2, col: 0, dir: .across), PlacedWord(word: "HIS", row: 2, col: 1, dir: .down), PlacedWord(word: "SIE", row: 4, col: 1, dir: .across), PlacedWord(word: "SEN", row: 1, col: 4, dir: .down)]),
    Level(rows: 7, cols: 5, letters: ["P", "L", "A", "T", "E"],
          words: [PlacedWord(word: "LATE", row: 2, col: 0, dir: .across), PlacedWord(word: "PLATE", row: 1, col: 0, dir: .down), PlacedWord(word: "TAPE", row: 2, col: 2, dir: .down), PlacedWord(word: "PAT", row: 4, col: 2, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["T", "R", "A", "C", "K"],
          words: [PlacedWord(word: "RACK", row: 2, col: 0, dir: .across), PlacedWord(word: "TRACK", row: 1, col: 0, dir: .down), PlacedWord(word: "CART", row: 2, col: 2, dir: .down), PlacedWord(word: "RAT", row: 4, col: 2, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["S", "C", "A", "L", "E"],
          words: [PlacedWord(word: "LACE", row: 2, col: 0, dir: .across), PlacedWord(word: "SCALE", row: 1, col: 2, dir: .down), PlacedWord(word: "SEAL", row: 5, col: 1, dir: .across), PlacedWord(word: "ELS", row: 1, col: 0, dir: .down)]),
    Level(rows: 7, cols: 4, letters: ["P", "R", "I", "N", "T"],
          words: [PlacedWord(word: "TRIP", row: 2, col: 0, dir: .across), PlacedWord(word: "PRINT", row: 1, col: 1, dir: .down), PlacedWord(word: "PIN", row: 2, col: 3, dir: .down)]),
    Level(rows: 7, cols: 5, letters: ["C", "R", "A", "F", "T"],
          words: [PlacedWord(word: "FACT", row: 1, col: 0, dir: .across), PlacedWord(word: "CRAFT", row: 1, col: 2, dir: .down), PlacedWord(word: "CART", row: 3, col: 1, dir: .across), PlacedWord(word: "CAT", row: 5, col: 0, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["S", "M", "I", "L", "E"],
          words: [PlacedWord(word: "LIMES", row: 2, col: 0, dir: .across), PlacedWord(word: "SMILE", row: 1, col: 2, dir: .down), PlacedWord(word: "LIME", row: 2, col: 0, dir: .down), PlacedWord(word: "SEMI", row: 2, col: 4, dir: .down)]),
    Level(rows: 7, cols: 4, letters: ["F", "R", "O", "S", "T"],
          words: [PlacedWord(word: "SOFT", row: 1, col: 0, dir: .across), PlacedWord(word: "FROST", row: 1, col: 2, dir: .down), PlacedWord(word: "SORT", row: 1, col: 0, dir: .down)]),
    Level(rows: 8, cols: 6, letters: ["B", "R", "A", "V", "E"],
          words: [PlacedWord(word: "BARE", row: 2, col: 0, dir: .across), PlacedWord(word: "BRAVE", row: 2, col: 0, dir: .down), PlacedWord(word: "BEAR", row: 1, col: 3, dir: .down), PlacedWord(word: "BAR", row: 1, col: 3, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["Q", "U", "I", "E", "T"],
          words: [PlacedWord(word: "QUITE", row: 1, col: 0, dir: .across), PlacedWord(word: "QUIET", row: 1, col: 0, dir: .down), PlacedWord(word: "TUE", row: 1, col: 3, dir: .down), PlacedWord(word: "TIE", row: 5, col: 0, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["P", "L", "A", "T", "E", "S"],
          words: [PlacedWord(word: "PLATE", row: 2, col: 0, dir: .across), PlacedWord(word: "STEAL", row: 1, col: 3, dir: .down), PlacedWord(word: "LEAST", row: 2, col: 1, dir: .down), PlacedWord(word: "SALT", row: 5, col: 1, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["S", "T", "R", "E", "A", "M"],
          words: [PlacedWord(word: "MASTER", row: 1, col: 0, dir: .across), PlacedWord(word: "STREAM", row: 1, col: 2, dir: .down), PlacedWord(word: "STEAM", row: 4, col: 0, dir: .across), PlacedWord(word: "SMART", row: 6, col: 1, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["B", "R", "I", "G", "H", "T"],
          words: [PlacedWord(word: "BIRTH", row: 1, col: 0, dir: .across), PlacedWord(word: "BRIGHT", row: 1, col: 0, dir: .down), PlacedWord(word: "RIGHT", row: 1, col: 2, dir: .down), PlacedWord(word: "HIT", row: 1, col: 4, dir: .down)]),
    Level(rows: 9, cols: 6, letters: ["F", "O", "R", "E", "S", "T"],
          words: [PlacedWord(word: "FOSTER", row: 2, col: 0, dir: .across), PlacedWord(word: "FOREST", row: 2, col: 0, dir: .down), PlacedWord(word: "STORE", row: 2, col: 2, dir: .down), PlacedWord(word: "FROST", row: 1, col: 5, dir: .down)]),
    Level(rows: 9, cols: 6, letters: ["G", "A", "R", "D", "E", "N"],
          words: [PlacedWord(word: "DANGER", row: 2, col: 0, dir: .across), PlacedWord(word: "GARDEN", row: 1, col: 1, dir: .down), PlacedWord(word: "RANGED", row: 2, col: 5, dir: .down), PlacedWord(word: "GRAND", row: 2, col: 3, dir: .down)]),
    Level(rows: 8, cols: 6, letters: ["C", "A", "S", "T", "L", "E"],
          words: [PlacedWord(word: "SCALE", row: 1, col: 0, dir: .across), PlacedWord(word: "CASTLE", row: 1, col: 1, dir: .down), PlacedWord(word: "STEAL", row: 3, col: 1, dir: .across), PlacedWord(word: "LEAST", row: 5, col: 1, dir: .across)]),
    Level(rows: 7, cols: 6, letters: ["I", "S", "L", "A", "N", "D"],
          words: [PlacedWord(word: "NAIL", row: 2, col: 0, dir: .across), PlacedWord(word: "SAID", row: 1, col: 1, dir: .down), PlacedWord(word: "LAID", row: 2, col: 3, dir: .down), PlacedWord(word: "AND", row: 3, col: 3, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["B", "R", "I", "D", "G", "E"],
          words: [PlacedWord(word: "BRIDE", row: 2, col: 0, dir: .across), PlacedWord(word: "BRIDGE", row: 2, col: 0, dir: .down), PlacedWord(word: "RIDGE", row: 1, col: 2, dir: .down), PlacedWord(word: "GIED", row: 4, col: 2, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["D", "E", "S", "E", "R", "T"],
          words: [PlacedWord(word: "RESET", row: 2, col: 0, dir: .across), PlacedWord(word: "DESERT", row: 1, col: 1, dir: .down), PlacedWord(word: "TREED", row: 2, col: 4, dir: .down), PlacedWord(word: "SEED", row: 4, col: 3, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["P", "L", "A", "N", "E", "T"],
          words: [PlacedWord(word: "PLANE", row: 2, col: 0, dir: .across), PlacedWord(word: "PLANET", row: 2, col: 0, dir: .down), PlacedWord(word: "PANEL", row: 1, col: 2, dir: .down), PlacedWord(word: "LANE", row: 5, col: 2, dir: .across)]),
    Level(rows: 9, cols: 5, letters: ["W", "I", "N", "T", "E", "R"],
          words: [PlacedWord(word: "WRITE", row: 2, col: 0, dir: .across), PlacedWord(word: "WINTER", row: 2, col: 0, dir: .down), PlacedWord(word: "INTER", row: 2, col: 2, dir: .down), PlacedWord(word: "RENT", row: 1, col: 4, dir: .down), PlacedWord(word: "TIER", row: 5, col: 0, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["S", "P", "R", "I", "N", "G"],
          words: [PlacedWord(word: "GRIP", row: 2, col: 0, dir: .across), PlacedWord(word: "SPRING", row: 1, col: 3, dir: .down), PlacedWord(word: "SPIN", row: 4, col: 1, dir: .across), PlacedWord(word: "PING", row: 6, col: 0, dir: .across), PlacedWord(word: "SRI", row: 1, col: 3, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["S", "U", "M", "M", "E", "R"],
          words: [PlacedWord(word: "SERUM", row: 1, col: 0, dir: .across), PlacedWord(word: "SUMMER", row: 1, col: 0, dir: .down), PlacedWord(word: "USER", row: 1, col: 3, dir: .down), PlacedWord(word: "MEM", row: 3, col: 2, dir: .across), PlacedWord(word: "ERS", row: 5, col: 0, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["M", "O", "T", "H", "E", "R"],
          words: [PlacedWord(word: "OTHER", row: 2, col: 0, dir: .across), PlacedWord(word: "MOTHER", row: 1, col: 0, dir: .down), PlacedWord(word: "THEM", row: 1, col: 2, dir: .down), PlacedWord(word: "HOME", row: 4, col: 0, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["F", "A", "T", "H", "E", "R"],
          words: [PlacedWord(word: "AFTER", row: 2, col: 0, dir: .across), PlacedWord(word: "FATHER", row: 1, col: 0, dir: .down), PlacedWord(word: "HEART", row: 1, col: 3, dir: .down), PlacedWord(word: "EARTH", row: 5, col: 0, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["T", "E", "A", "C", "H", "E", "R"],
          words: [PlacedWord(word: "CREATE", row: 2, col: 0, dir: .across), PlacedWord(word: "TEACHER", row: 1, col: 2, dir: .down), PlacedWord(word: "HEATER", row: 1, col: 5, dir: .down), PlacedWord(word: "EARTH", row: 7, col: 0, dir: .across), PlacedWord(word: "THREE", row: 5, col: 1, dir: .across)]),
    Level(rows: 8, cols: 4, letters: ["D", "O", "C", "T", "O", "R"],
          words: [PlacedWord(word: "ROOT", row: 2, col: 0, dir: .across), PlacedWord(word: "DOCTOR", row: 1, col: 1, dir: .down), PlacedWord(word: "DOOR", row: 5, col: 0, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["W", "O", "N", "D", "E", "R"],
          words: [PlacedWord(word: "OWNER", row: 2, col: 0, dir: .across), PlacedWord(word: "WONDER", row: 1, col: 0, dir: .down), PlacedWord(word: "ROWED", row: 2, col: 4, dir: .down), PlacedWord(word: "NOWED", row: 2, col: 2, dir: .down), PlacedWord(word: "ROD", row: 6, col: 0, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["M", "A", "R", "K", "E", "T"],
          words: [PlacedWord(word: "MAKER", row: 1, col: 0, dir: .across), PlacedWord(word: "MARKET", row: 1, col: 0, dir: .down), PlacedWord(word: "RATE", row: 1, col: 4, dir: .down), PlacedWord(word: "TEAR", row: 6, col: 0, dir: .across), PlacedWord(word: "TREK", row: 4, col: 2, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["B", "U", "T", "T", "E", "R"],
          words: [PlacedWord(word: "TRUE", row: 2, col: 0, dir: .across), PlacedWord(word: "BUTTER", row: 1, col: 2, dir: .down), PlacedWord(word: "TUBE", row: 2, col: 0, dir: .down), PlacedWord(word: "TUB", row: 4, col: 2, dir: .across)]),
    Level(rows: 6, cols: 8, letters: ["C", "O", "T", "T", "A", "G", "E"],
          words: [PlacedWord(word: "COTTAGE", row: 1, col: 0, dir: .across), PlacedWord(word: "COAT", row: 1, col: 0, dir: .down), PlacedWord(word: "GOAT", row: 1, col: 5, dir: .down), PlacedWord(word: "GATE", row: 3, col: 4, dir: .across), PlacedWord(word: "TEA", row: 1, col: 2, dir: .down)]),
    Level(rows: 7, cols: 7, letters: ["H", "U", "N", "T", "E", "R"],
          words: [PlacedWord(word: "TUNER", row: 2, col: 0, dir: .across), PlacedWord(word: "TRUE", row: 2, col: 0, dir: .down), PlacedWord(word: "RENT", row: 1, col: 3, dir: .down), PlacedWord(word: "THEN", row: 4, col: 3, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["M", "A", "S", "T", "E", "R"],
          words: [PlacedWord(word: "STREAM", row: 2, col: 0, dir: .across), PlacedWord(word: "MASTER", row: 1, col: 4, dir: .down), PlacedWord(word: "STEAM", row: 2, col: 0, dir: .down), PlacedWord(word: "STEM", row: 4, col: 3, dir: .across), PlacedWord(word: "MART", row: 6, col: 2, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["P", "O", "S", "T", "E", "R"],
          words: [PlacedWord(word: "SPORT", row: 1, col: 0, dir: .across), PlacedWord(word: "POSTER", row: 1, col: 1, dir: .down), PlacedWord(word: "ROPES", row: 1, col: 3, dir: .down), PlacedWord(word: "PEST", row: 3, col: 3, dir: .across), PlacedWord(word: "STEP", row: 5, col: 3, dir: .across)]),
    Level(rows: 9, cols: 7, letters: ["T", "R", "A", "V", "E", "L"],
          words: [PlacedWord(word: "LATER", row: 2, col: 0, dir: .across), PlacedWord(word: "TRAVEL", row: 2, col: 2, dir: .down), PlacedWord(word: "ALERT", row: 1, col: 0, dir: .down), PlacedWord(word: "ALTER", row: 4, col: 2, dir: .across), PlacedWord(word: "RATE", row: 2, col: 4, dir: .down)]),
    Level(rows: 9, cols: 7, letters: ["M", "O", "R", "N", "I", "N", "G"],
          words: [PlacedWord(word: "MINOR", row: 2, col: 0, dir: .across), PlacedWord(word: "MORNING", row: 1, col: 3, dir: .down), PlacedWord(word: "RING", row: 1, col: 1, dir: .down), PlacedWord(word: "NORM", row: 4, col: 3, dir: .across), PlacedWord(word: "MING", row: 6, col: 1, dir: .across)]),
    Level(rows: 10, cols: 6, letters: ["E", "V", "E", "N", "I", "N", "G"],
          words: [PlacedWord(word: "ENGINE", row: 2, col: 0, dir: .across), PlacedWord(word: "EVENING", row: 2, col: 0, dir: .down), PlacedWord(word: "GIVEN", row: 2, col: 2, dir: .down), PlacedWord(word: "GIVE", row: 8, col: 0, dir: .across), PlacedWord(word: "GENE", row: 1, col: 5, dir: .down)]),
    Level(rows: 9, cols: 6, letters: ["P", "I", "C", "T", "U", "R", "E"],
          words: [PlacedWord(word: "PRICE", row: 2, col: 0, dir: .across), PlacedWord(word: "PICTURE", row: 1, col: 2, dir: .down), PlacedWord(word: "RICE", row: 6, col: 2, dir: .across), PlacedWord(word: "TIER", row: 4, col: 2, dir: .across), PlacedWord(word: "PURE", row: 2, col: 0, dir: .down)]),
    Level(rows: 9, cols: 8, letters: ["W", "E", "A", "T", "H", "E", "R"],
          words: [PlacedWord(word: "HEATER", row: 2, col: 0, dir: .across), PlacedWord(word: "WEATHER", row: 1, col: 1, dir: .down), PlacedWord(word: "THREE", row: 2, col: 3, dir: .down), PlacedWord(word: "EARTH", row: 5, col: 3, dir: .across), PlacedWord(word: "HERE", row: 6, col: 0, dir: .across)]),
    Level(rows: 9, cols: 5, letters: ["J", "O", "U", "R", "N", "E", "Y"],
          words: [PlacedWord(word: "ENJOY", row: 2, col: 0, dir: .across), PlacedWord(word: "JOURNEY", row: 1, col: 3, dir: .down), PlacedWord(word: "JUNE", row: 5, col: 1, dir: .across), PlacedWord(word: "JURY", row: 7, col: 0, dir: .across), PlacedWord(word: "YEN", row: 1, col: 0, dir: .down)]),
    Level(rows: 7, cols: 7, letters: ["M", "E", "E", "T", "I", "N", "G"],
          words: [PlacedWord(word: "MEETING", row: 2, col: 0, dir: .across), PlacedWord(word: "TIME", row: 2, col: 3, dir: .down), PlacedWord(word: "GENE", row: 1, col: 1, dir: .down), PlacedWord(word: "MINE", row: 4, col: 3, dir: .across)]),
    Level(rows: 10, cols: 7, letters: ["R", "E", "A", "D", "I", "N", "G"],
          words: [PlacedWord(word: "GRAINED", row: 2, col: 0, dir: .across), PlacedWord(word: "READING", row: 2, col: 1, dir: .down), PlacedWord(word: "DANGER", row: 2, col: 6, dir: .down), PlacedWord(word: "DARING", row: 5, col: 1, dir: .across), PlacedWord(word: "GRAND", row: 8, col: 1, dir: .across), PlacedWord(word: "END", row: 1, col: 4, dir: .down)]),
    Level(rows: 9, cols: 6, letters: ["W", "A", "L", "K", "I", "N", "G"],
          words: [PlacedWord(word: "WAKING", row: 1, col: 0, dir: .across), PlacedWord(word: "WALKING", row: 1, col: 0, dir: .down), PlacedWord(word: "LAKING", row: 3, col: 0, dir: .across), PlacedWord(word: "GAIN", row: 7, col: 0, dir: .across), PlacedWord(word: "ING", row: 5, col: 0, dir: .across)]),
    Level(rows: 7, cols: 8, letters: ["E", "V", "E", "R", "E", "S", "T"],
          words: [PlacedWord(word: "SEVERE", row: 1, col: 0, dir: .across), PlacedWord(word: "SERVE", row: 1, col: 0, dir: .down), PlacedWord(word: "VERSE", row: 1, col: 2, dir: .down), PlacedWord(word: "RESET", row: 1, col: 4, dir: .down), PlacedWord(word: "EVER", row: 4, col: 4, dir: .across), PlacedWord(word: "EVE", row: 5, col: 0, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["F", "R", "E", "E", "D", "O", "M"],
          words: [PlacedWord(word: "FORMED", row: 2, col: 0, dir: .across), PlacedWord(word: "FREEDOM", row: 2, col: 0, dir: .down), PlacedWord(word: "FREED", row: 1, col: 2, dir: .down), PlacedWord(word: "DEER", row: 1, col: 4, dir: .down), PlacedWord(word: "REED", row: 4, col: 4, dir: .across), PlacedWord(word: "MERE", row: 8, col: 0, dir: .across)]),
    Level(rows: 9, cols: 7, letters: ["S", "T", "A", "T", "I", "O", "N"],
          words: [PlacedWord(word: "SAINT", row: 2, col: 0, dir: .across), PlacedWord(word: "STATION", row: 1, col: 4, dir: .down), PlacedWord(word: "SATIN", row: 2, col: 0, dir: .down), PlacedWord(word: "ATIS", row: 4, col: 3, dir: .across), PlacedWord(word: "ANTI", row: 7, col: 3, dir: .across), PlacedWord(word: "IST", row: 5, col: 0, dir: .across)]),
    Level(rows: 10, cols: 6, letters: ["V", "I", "C", "T", "O", "R", "Y"],
          words: [PlacedWord(word: "VICTOR", row: 2, col: 0, dir: .across), PlacedWord(word: "VICTORY", row: 2, col: 0, dir: .down), PlacedWord(word: "TRIO", row: 2, col: 3, dir: .down), PlacedWord(word: "CITY", row: 4, col: 2, dir: .across), PlacedWord(word: "TROY", row: 1, col: 5, dir: .down), PlacedWord(word: "RIO", row: 7, col: 0, dir: .across)]),
    Level(rows: 7, cols: 8, letters: ["M", "Y", "S", "T", "E", "R", "Y"],
          words: [PlacedWord(word: "MYSTERY", row: 2, col: 0, dir: .across), PlacedWord(word: "REST", row: 1, col: 4, dir: .down), PlacedWord(word: "STEM", row: 2, col: 2, dir: .down), PlacedWord(word: "TERM", row: 4, col: 4, dir: .across), PlacedWord(word: "MET", row: 2, col: 0, dir: .down)]),
    Level(rows: 8, cols: 5, letters: ["H", "I", "S", "T", "O", "R", "Y"],
          words: [PlacedWord(word: "SHORT", row: 2, col: 0, dir: .across), PlacedWord(word: "SHIRT", row: 2, col: 0, dir: .down), PlacedWord(word: "STORY", row: 1, col: 4, dir: .down), PlacedWord(word: "HOST", row: 1, col: 2, dir: .down), PlacedWord(word: "TRIO", row: 6, col: 0, dir: .across), PlacedWord(word: "IST", row: 4, col: 0, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["F", "A", "C", "T", "O", "R", "Y"],
          words: [PlacedWord(word: "FACTOR", row: 2, col: 0, dir: .across), PlacedWord(word: "FACTORY", row: 2, col: 0, dir: .down), PlacedWord(word: "ACTOR", row: 1, col: 2, dir: .down), PlacedWord(word: "CRAFT", row: 1, col: 5, dir: .down), PlacedWord(word: "TAR", row: 5, col: 0, dir: .across), PlacedWord(word: "FAR", row: 4, col: 5, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["G", "A", "L", "L", "E", "R", "Y"],
          words: [PlacedWord(word: "LARGELY", row: 2, col: 0, dir: .across), PlacedWord(word: "ALLERGY", row: 1, col: 0, dir: .down), PlacedWord(word: "GALLERY", row: 2, col: 3, dir: .down), PlacedWord(word: "REALLY", row: 5, col: 0, dir: .across), PlacedWord(word: "RALLY", row: 7, col: 3, dir: .across), PlacedWord(word: "ALL", row: 1, col: 5, dir: .down)]),
    Level(rows: 9, cols: 7, letters: ["S", "T", "U", "D", "E", "N", "T"],
          words: [PlacedWord(word: "TUNED", row: 2, col: 0, dir: .across), PlacedWord(word: "STUDENT", row: 1, col: 0, dir: .down), PlacedWord(word: "SNED", row: 1, col: 2, dir: .down), PlacedWord(word: "TUNE", row: 7, col: 0, dir: .across), PlacedWord(word: "DUST", row: 2, col: 4, dir: .down), PlacedWord(word: "SET", row: 4, col: 4, dir: .across)]),
    Level(rows: 9, cols: 8, letters: ["T", "E", "A", "C", "H", "E", "R"],
          words: [PlacedWord(word: "HEATER", row: 2, col: 0, dir: .across), PlacedWord(word: "TEACHER", row: 1, col: 1, dir: .down), PlacedWord(word: "CREATE", row: 1, col: 5, dir: .down), PlacedWord(word: "THREE", row: 2, col: 3, dir: .down), PlacedWord(word: "REACH", row: 4, col: 3, dir: .across), PlacedWord(word: "HERE", row: 6, col: 0, dir: .across)]),
    Level(rows: 10, cols: 7, letters: ["M", "A", "N", "A", "G", "E", "R"],
          words: [PlacedWord(word: "GERMAN", row: 2, col: 0, dir: .across), PlacedWord(word: "MANAGER", row: 2, col: 3, dir: .down), PlacedWord(word: "MANAGE", row: 4, col: 1, dir: .across), PlacedWord(word: "ANGER", row: 6, col: 1, dir: .across), PlacedWord(word: "ARENA", row: 8, col: 2, dir: .across), PlacedWord(word: "AGE", row: 1, col: 0, dir: .down)]),
    Level(rows: 7, cols: 8, letters: ["A", "R", "T", "I", "S", "T", "S"],
          words: [PlacedWord(word: "ARTIST", row: 2, col: 0, dir: .across), PlacedWord(word: "START", row: 1, col: 2, dir: .down), PlacedWord(word: "ATIS", row: 2, col: 0, dir: .down), PlacedWord(word: "TARS", row: 2, col: 5, dir: .down), PlacedWord(word: "SIS", row: 5, col: 5, dir: .across), PlacedWord(word: "ART", row: 3, col: 5, dir: .across)]),
    Level(rows: 9, cols: 8, letters: ["P", "A", "R", "T", "N", "E", "R"],
          words: [PlacedWord(word: "PARENT", row: 1, col: 0, dir: .across), PlacedWord(word: "PARTNER", row: 1, col: 0, dir: .down), PlacedWord(word: "REAR", row: 1, col: 2, dir: .down), PlacedWord(word: "EARN", row: 6, col: 0, dir: .across), PlacedWord(word: "TRAP", row: 1, col: 5, dir: .down), PlacedWord(word: "TAPE", row: 3, col: 4, dir: .across)]),
    Level(rows: 10, cols: 6, letters: ["M", "O", "N", "S", "T", "E", "R"],
          words: [PlacedWord(word: "MENTOR", row: 2, col: 0, dir: .across), PlacedWord(word: "MONSTER", row: 2, col: 0, dir: .down), PlacedWord(word: "STONE", row: 1, col: 3, dir: .down), PlacedWord(word: "SENT", row: 5, col: 2, dir: .across), PlacedWord(word: "RENT", row: 2, col: 5, dir: .down), PlacedWord(word: "ROSE", row: 8, col: 0, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["P", "A", "L", "A", "C", "E", "S"],
          words: [PlacedWord(word: "PALACE", row: 2, col: 0, dir: .across), PlacedWord(word: "PLACE", row: 2, col: 0, dir: .down), PlacedWord(word: "SCALE", row: 1, col: 4, dir: .down), PlacedWord(word: "ALAS", row: 1, col: 2, dir: .down), PlacedWord(word: "SALE", row: 4, col: 2, dir: .across), PlacedWord(word: "ELS", row: 6, col: 0, dir: .across)]),
    Level(rows: 6, cols: 4, letters: ["T", "R", "O", "P", "H", "Y"],
          words: [PlacedWord(word: "PORT", row: 2, col: 0, dir: .across), PlacedWord(word: "TROY", row: 1, col: 2, dir: .down), PlacedWord(word: "THY", row: 4, col: 0, dir: .across), PlacedWord(word: "POT", row: 2, col: 0, dir: .down)]),
    Level(rows: 8, cols: 8, letters: ["S", "T", "O", "R", "I", "E", "S"],
          words: [PlacedWord(word: "SISTER", row: 2, col: 0, dir: .across), PlacedWord(word: "RESIST", row: 1, col: 4, dir: .down), PlacedWord(word: "STORE", row: 2, col: 0, dir: .down), PlacedWord(word: "SITE", row: 2, col: 2, dir: .down), PlacedWord(word: "TIRE", row: 6, col: 4, dir: .across), PlacedWord(word: "TRIO", row: 4, col: 2, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["M", "O", "U", "N", "T", "A", "I", "N"],
          words: [PlacedWord(word: "NATION", row: 2, col: 0, dir: .across), PlacedWord(word: "MOUNTAIN", row: 1, col: 4, dir: .down), PlacedWord(word: "AMOUNT", row: 2, col: 1, dir: .down), PlacedWord(word: "UNION", row: 4, col: 3, dir: .across), PlacedWord(word: "INTO", row: 7, col: 4, dir: .across), PlacedWord(word: "ANN", row: 8, col: 2, dir: .across), PlacedWord(word: "NUT", row: 5, col: 0, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["V", "A", "C", "A", "T", "I", "O", "N"],
          words: [PlacedWord(word: "ACTION", row: 2, col: 0, dir: .across), PlacedWord(word: "VACATION", row: 1, col: 0, dir: .down), PlacedWord(word: "INTO", row: 2, col: 3, dir: .down), PlacedWord(word: "ANTI", row: 1, col: 5, dir: .down), PlacedWord(word: "NOVA", row: 8, col: 0, dir: .across), PlacedWord(word: "ANT", row: 1, col: 5, dir: .across), PlacedWord(word: "ION", row: 6, col: 0, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["B", "I", "R", "T", "H", "D", "A", "Y"],
          words: [PlacedWord(word: "HYBRID", row: 2, col: 0, dir: .across), PlacedWord(word: "BIRTHDAY", row: 1, col: 4, dir: .down), PlacedWord(word: "BIRTH", row: 2, col: 2, dir: .down), PlacedWord(word: "DIARY", row: 8, col: 0, dir: .across), PlacedWord(word: "HAIRY", row: 2, col: 0, dir: .down), PlacedWord(word: "HARD", row: 5, col: 4, dir: .across), PlacedWord(word: "AIR", row: 7, col: 4, dir: .across)]),
    Level(rows: 7, cols: 10, letters: ["A", "T", "T", "I", "T", "U", "D", "E"],
          words: [PlacedWord(word: "ATTITUDE", row: 1, col: 0, dir: .across), PlacedWord(word: "AUDIT", row: 1, col: 0, dir: .down), PlacedWord(word: "TIDE", row: 1, col: 2, dir: .down), PlacedWord(word: "DATE", row: 1, col: 6, dir: .down), PlacedWord(word: "TIED", row: 1, col: 4, dir: .down), PlacedWord(word: "EDIT", row: 4, col: 6, dir: .across), PlacedWord(word: "EAT", row: 3, col: 4, dir: .across)]),
    Level(rows: 8, cols: 11, letters: ["B", "R", "I", "L", "L", "I", "A", "N", "T"],
          words: [PlacedWord(word: "BRILLIANT", row: 2, col: 0, dir: .across), PlacedWord(word: "TRIBAL", row: 1, col: 1, dir: .down), PlacedWord(word: "BRAIN", row: 4, col: 1, dir: .across), PlacedWord(word: "TRAIL", row: 2, col: 8, dir: .down), PlacedWord(word: "BLAIR", row: 1, col: 4, dir: .down), PlacedWord(word: "TRIAL", row: 5, col: 6, dir: .across), PlacedWord(word: "LAT", row: 1, col: 6, dir: .down)]),
    Level(rows: 7, cols: 9, letters: ["S", "T", "R", "E", "N", "G", "T", "H"],
          words: [PlacedWord(word: "STRENGTH", row: 2, col: 0, dir: .across), PlacedWord(word: "TENT", row: 2, col: 1, dir: .down), PlacedWord(word: "THEN", row: 2, col: 6, dir: .down), PlacedWord(word: "HERS", row: 1, col: 3, dir: .down), PlacedWord(word: "RENT", row: 4, col: 5, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["T", "R", "E", "A", "S", "U", "R", "E"],
          words: [PlacedWord(word: "EASTER", row: 2, col: 0, dir: .across), PlacedWord(word: "TREASURE", row: 1, col: 5, dir: .down), PlacedWord(word: "ARREST", row: 2, col: 1, dir: .down), PlacedWord(word: "RESET", row: 5, col: 3, dir: .across), PlacedWord(word: "TARS", row: 7, col: 3, dir: .across), PlacedWord(word: "TEAR", row: 2, col: 3, dir: .down), PlacedWord(word: "ERS", row: 3, col: 5, dir: .across)]),
    Level(rows: 8, cols: 8, letters: ["P", "R", "E", "S", "E", "N", "T", "S"],
          words: [PlacedWord(word: "PRESENT", row: 2, col: 0, dir: .across), PlacedWord(word: "TEENS", row: 1, col: 2, dir: .down), PlacedWord(word: "ENTER", row: 2, col: 4, dir: .down), PlacedWord(word: "SPENT", row: 1, col: 0, dir: .down), PlacedWord(word: "PRESS", row: 6, col: 3, dir: .across), PlacedWord(word: "TEEN", row: 4, col: 4, dir: .across), PlacedWord(word: "TEE", row: 2, col: 6, dir: .down)]),
    Level(rows: 10, cols: 8, letters: ["A", "I", "R", "P", "L", "A", "N", "E"],
          words: [PlacedWord(word: "AERIAL", row: 2, col: 0, dir: .across), PlacedWord(word: "AIRPLANE", row: 1, col: 3, dir: .down), PlacedWord(word: "ALPINE", row: 2, col: 0, dir: .down), PlacedWord(word: "LINEAR", row: 2, col: 5, dir: .down), PlacedWord(word: "PANEL", row: 4, col: 3, dir: .across), PlacedWord(word: "EARN", row: 7, col: 0, dir: .across), PlacedWord(word: "ALAN", row: 6, col: 3, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["D", "E", "S", "C", "R", "I", "B", "E"],
          words: [PlacedWord(word: "BESIDE", row: 2, col: 0, dir: .across), PlacedWord(word: "DESCRIBE", row: 1, col: 1, dir: .down), PlacedWord(word: "DESIRE", row: 2, col: 4, dir: .down), PlacedWord(word: "BRIDE", row: 6, col: 3, dir: .across), PlacedWord(word: "DEER", row: 8, col: 0, dir: .across), PlacedWord(word: "SEED", row: 4, col: 4, dir: .across), PlacedWord(word: "ICE", row: 4, col: 0, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["I", "N", "T", "E", "R", "N", "E", "T"],
          words: [PlacedWord(word: "INTENT", row: 2, col: 0, dir: .across), PlacedWord(word: "ENTIRE", row: 1, col: 1, dir: .down), PlacedWord(word: "INTER", row: 1, col: 4, dir: .down), PlacedWord(word: "INNER", row: 4, col: 1, dir: .across), PlacedWord(word: "TENT", row: 6, col: 0, dir: .across)]),
    Level(rows: 8, cols: 10, letters: ["E", "V", "E", "R", "Y", "D", "A", "Y"],
          words: [PlacedWord(word: "EVERYDAY", row: 2, col: 0, dir: .across), PlacedWord(word: "EARED", row: 2, col: 0, dir: .down), PlacedWord(word: "EVERY", row: 2, col: 2, dir: .down), PlacedWord(word: "READY", row: 5, col: 2, dir: .across), PlacedWord(word: "EYED", row: 1, col: 7, dir: .down), PlacedWord(word: "ERA", row: 1, col: 7, dir: .across), PlacedWord(word: "EYE", row: 1, col: 4, dir: .down)]),
    Level(rows: 8, cols: 8, letters: ["D", "A", "U", "G", "H", "T", "E", "R"],
          words: [PlacedWord(word: "HURTED", row: 2, col: 0, dir: .across), PlacedWord(word: "THREAD", row: 1, col: 0, dir: .down), PlacedWord(word: "HEART", row: 1, col: 4, dir: .down), PlacedWord(word: "TRADE", row: 1, col: 2, dir: .down), PlacedWord(word: "TEAR", row: 5, col: 4, dir: .across), PlacedWord(word: "AGE", row: 5, col: 0, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["S", "O", "U", "T", "H", "E", "R", "N"],
          words: [PlacedWord(word: "HONEST", row: 2, col: 0, dir: .across), PlacedWord(word: "SOUTHERN", row: 1, col: 1, dir: .down), PlacedWord(word: "STONE", row: 2, col: 4, dir: .down), PlacedWord(word: "ROUTE", row: 4, col: 3, dir: .across), PlacedWord(word: "NORTH", row: 8, col: 1, dir: .across), PlacedWord(word: "REST", row: 6, col: 3, dir: .across), PlacedWord(word: "SHE", row: 5, col: 0, dir: .across)]),
    Level(rows: 8, cols: 11, letters: ["A", "V", "A", "I", "L", "A", "B", "L", "E"],
          words: [PlacedWord(word: "AVAILABLE", row: 2, col: 0, dir: .across), PlacedWord(word: "LIABLE", row: 1, col: 3, dir: .down), PlacedWord(word: "LABEL", row: 1, col: 0, dir: .down), PlacedWord(word: "ALIVE", row: 2, col: 5, dir: .down), PlacedWord(word: "EVIL", row: 2, col: 8, dir: .down), PlacedWord(word: "LIVE", row: 5, col: 3, dir: .across), PlacedWord(word: "BILL", row: 4, col: 7, dir: .across)]),
    Level(rows: 10, cols: 9, letters: ["A", "D", "V", "E", "N", "T", "U", "R", "E"],
          words: [PlacedWord(word: "VENTURE", row: 2, col: 0, dir: .across), PlacedWord(word: "VETERAN", row: 2, col: 0, dir: .down), PlacedWord(word: "TURNED", row: 2, col: 3, dir: .down), PlacedWord(word: "ADVERT", row: 7, col: 2, dir: .across), PlacedWord(word: "RENTED", row: 4, col: 3, dir: .across), PlacedWord(word: "TREND", row: 1, col: 5, dir: .down), PlacedWord(word: "EARN", row: 5, col: 0, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["B", "I", "R", "T", "H", "R", "A", "T", "E"],
          words: [PlacedWord(word: "THREAT", row: 1, col: 0, dir: .across), PlacedWord(word: "RATHER", row: 1, col: 2, dir: .down), PlacedWord(word: "BREATH", row: 5, col: 0, dir: .across), PlacedWord(word: "TRIBE", row: 3, col: 2, dir: .across), PlacedWord(word: "TEA", row: 1, col: 0, dir: .down), PlacedWord(word: "TAB", row: 1, col: 5, dir: .down)]),
    Level(rows: 8, cols: 8, letters: ["B", "R", "I", "G", "H", "T", "E", "S", "T"],
          words: [PlacedWord(word: "BRIGHT", row: 2, col: 0, dir: .across), PlacedWord(word: "THEIRS", row: 1, col: 4, dir: .down), PlacedWord(word: "TIGHTS", row: 1, col: 2, dir: .down), PlacedWord(word: "THEIR", row: 4, col: 1, dir: .across), PlacedWord(word: "SITE", row: 6, col: 4, dir: .across), PlacedWord(word: "ERS", row: 6, col: 0, dir: .across)]),
    Level(rows: 7, cols: 9, letters: ["E", "V", "E", "R", "G", "R", "E", "E", "N"],
          words: [PlacedWord(word: "REVENGE", row: 2, col: 0, dir: .across), PlacedWord(word: "GENRE", row: 1, col: 1, dir: .down), PlacedWord(word: "NEVER", row: 1, col: 3, dir: .down), PlacedWord(word: "NERVE", row: 1, col: 6, dir: .down), PlacedWord(word: "GREEN", row: 4, col: 0, dir: .across), PlacedWord(word: "GENE", row: 5, col: 5, dir: .across), PlacedWord(word: "REG", row: 3, col: 6, dir: .across)]),
    Level(rows: 11, cols: 8, letters: ["W", "O", "N", "D", "E", "R", "F", "U", "L"],
          words: [PlacedWord(word: "FOUNDER", row: 2, col: 0, dir: .across), PlacedWord(word: "WONDERFUL", row: 1, col: 1, dir: .down), PlacedWord(word: "REFUND", row: 1, col: 5, dir: .down), PlacedWord(word: "FLOWER", row: 9, col: 0, dir: .across), PlacedWord(word: "FLUED", row: 4, col: 3, dir: .across), PlacedWord(word: "UNDER", row: 6, col: 3, dir: .across), PlacedWord(word: "RED", row: 5, col: 0, dir: .across)]),
]

private let LEVEL_BONUS: [String: [String]] = [
    "CATS": ["ACT", "ACTS", "SCAT", "CATS"],
    "SPINE": ["PIN", "PIE", "SIP", "SNIP", "PIES", "PENS", "SINE", "PINE"],
    "HASTE": ["HEAT", "SET", "HAT", "TEA", "ATE", "ETA", "EAST", "EATS"],
    "WARMS": ["WARMS", "WARS", "ARMS", "MARS", "ARM", "MAR", "RAW", "WAR"],
    "CARES": ["RACE", "CARS", "EARS", "ACE", "ARC", "SCAR", "ARCS", "ACRE", "ACES"],
    "GRINDS": ["GRINDS", "GRID", "RIND", "DING", "RING", "GRIN", "RINGS"],
    "PLANETS": ["PLAN", "PLANT", "LEAN", "PLATE", "STEAL", "LANE", "TALE", "PELT"],
    "CRANESD": ["DANCE", "SCARE", "RACED", "CEDAR", "CANE", "ACRE", "RAN"],
    "STORED": ["RODE", "DOER", "STORE", "DOTES", "TROD", "ODES", "SORE", "TORE"],
    "TRAINSE": ["STARE", "RETAIN", "SATIRE", "INSERT", "STAIN", "RAIN", "RISE", "TIRE"],
    "GRACE": ["RACE", "ACRE", "CAGE", "GEAR", "EAR", "CAR", "ACE", "ARE"],
    "DREAM": ["DAME", "DARE", "READ", "ARED", "DEAR", "MADE", "EAR", "MAD"],
    "STORM": ["TOM"],
    "FLAME": ["LEAF", "FAME", "MEL", "MAE"],
    "LIGHT": ["LIT"],
    "STONE": ["SENT", "NOTE", "TONE", "ENS", "TEN", "NEO", "NOT", "TON"],
    "WATER": ["WARE", "RATE", "RAT", "ART", "ERA", "RAW", "ARE", "TAR"],
    "OCEAN": ["CON", "CAN", "ACE", "ONE", "NEO"],
    "PEACE": ["PEE", "CAP", "PAC", "ACE"],
    "SPACE": ["PACE", "CAPE", "SPEC", "SPA", "SEC", "PAC", "AES", "SEA"],
    "SHINE": ["SHE", "SIN", "ENS"],
    "PLATE": ["PALE", "TALE", "PET", "ATE", "ALT", "LAP", "TEA", "APT"],
    "TRACK": ["ACT", "ART", "ARC", "CAT", "CAR", "TAR"],
    "SCALE": ["CASE", "SALE", "CAL", "LAS", "AES", "SEA", "ACE", "SEC"],
    "PRINT": ["RIP", "TIN", "TIP", "TRI", "PIT"],
    "CRAFT": ["ART", "FAT", "ACT", "TAR", "CAR", "RAT", "ARC", "FAR"],
    "SMILE": ["SLIM", "ISLE", "MILE", "MEL", "LIS", "ELS", "LIE", "MIL"],
    "FROST": ["FORT", "FOR"],
    "BRAVE": ["AVE", "EAR", "BRA", "ERA", "ARE", "REV"],
    "QUIET": ["QUIT"],
    "PLATES": ["PASTE", "TALES", "TALE", "SEAT", "SEAL", "EATS", "ATES", "PALE"],
    "STREAM": ["EATS", "TEAR", "MART", "TERM", "REST", "SAME", "ARMS", "SEAT"],
    "BRIGHT": ["BIG", "TRI", "BIT"],
    "FOREST": ["ROSE", "FORT", "REST", "SORT", "SOFT", "SER", "TOE", "SET"],
    "GARDEN": ["RANGE", "GRADE", "ANGER", "GRAD", "READ", "ARED", "EARN", "DARE"],
    "CASTLE": ["TALES", "LACE", "TALE", "EAST", "SEAT", "LATE", "ATES", "LAST"],
    "ISLAND": ["ISLAND", "SAND", "DIAL", "SAIL", "LAND", "SAN", "DIS", "LIS"],
    "BRIDGE": ["BIRD", "RIDE", "BRED", "GRID", "BIG", "RID", "DIG", "GED"],
    "DESERT": ["TREE", "REED", "DEER", "REST", "SER", "ERS", "DEE", "SEE"],
    "PLANET": ["PLATE", "PLANT", "TAPE", "LATE", "PLAN", "TALE", "PALE", "LEAN"],
    "WINTER": ["WINE", "TIRE", "TWIN", "WENT", "WIRE", "TIE", "TIN", "WIN"],
    "SPRING": ["SING", "RING", "SIGN", "PIN", "PIG", "RIP", "ING", "SIG"],
    "SUMMER": ["SURE", "USE", "SER", "SUE", "SUM", "SUR"],
    "MOTHER": ["TERM", "HERO", "MORE", "MET", "TOE", "THE", "TOM", "HOT"],
    "FATHER": ["HART", "HEAR", "FARE", "TEAR", "HEAT", "FEAT", "FEAR", "FATE"],
    "TEACHER": ["TRACE", "TEACH", "REACH", "HEART", "THERE", "CHEAT", "CHART", "TREE"],
    "DOCTOR": ["CORD", "DOC", "ROD", "TOO", "COD", "DOT"],
    "WONDER": ["ROED", "NODE", "DOWN", "WORD", "DREW", "WORN", "DONE", "ONE"],
    "MARKET": ["MARK", "MAKE", "TERM", "TAKE", "META", "TEAM", "MART", "MATE"],
    "BUTTER": ["BUT", "TUE", "BET"],
    "COTTAGE": ["CAGE", "ACE", "GOT", "AGO", "AGE", "GET", "EAT", "CAT"],
    "HUNTER": ["HUNT", "HURT", "TUNE", "TURN", "RUTH", "NET", "TUE", "TEN"],
    "MASTER": ["SMART", "TEAR", "MEAT", "META", "RATE", "TERM", "TARS", "SEAT"],
    "POSTER": ["STORE", "TOPS", "POSE", "REST", "SPOT", "PORT", "POET", "ROPE"],
    "TRAVEL": ["REAL", "LATE", "TEAR", "TALE", "EARL", "EAR", "AVE", "ARE"],
    "MORNING": ["IRON", "MIN", "ING", "INN", "NON", "MON", "RIO", "ION"],
    "EVENING": ["NINE", "EVEN", "INN", "ING", "GEN", "EVE"],
    "PICTURE": ["TRIP", "CURE", "ERIC", "TRUE", "CITE", "RIPE", "CUTE", "TIRE"],
    "WEATHER": ["WATER", "THERE", "WHERE", "WHEAT", "HEART", "WEAR", "HEAT", "TEAR"],
    "JOURNEY": ["YOUR", "JOE", "NOR", "JOY", "OUR", "YOU", "ONE", "RUN"],
    "MEETING": ["ITEM", "TEEN", "TING", "MINT", "MING", "MEET", "GET", "MIN"],
    "READING": ["EARING", "RINGED", "GARDEN", "RANGED", "RIDGE", "GRADE", "ANGER", "RANGE"],
    "WALKING": ["WALING", "LAWING", "AWING", "ALIGN", "KING", "WALK", "WING", "LINK"],
    "EVEREST": ["TREE", "REST", "ERS", "SET", "SER", "TEE", "SEE", "REV"],
    "FREEDOM": ["FORM", "ROED", "MODE", "FEED", "FREE", "FORD", "DOME", "MORE"],
    "STATION": ["INTO", "SAO", "ANT", "ONS", "NOT", "SAT", "SIN", "SON"],
    "VICTORY": ["IVORY", "CRY", "TRY", "TRI", "TOY"],
    "MYSTERY": ["YET", "SET", "TRY", "SER", "YES", "ERS"],
    "HISTORY": ["HISTORY", "SHOT", "TROY", "SORT", "HIST", "THIS", "HIT", "ISO"],
    "FACTORY": ["FORTY", "FACT", "TRAY", "CART", "TROY", "FORT", "COAT", "ACT"],
    "GALLERY": ["LARGE", "LAYER", "LEGAL", "EARLY", "RELAY", "YEAR", "GREY", "RELY"],
    "STUDENT": ["USED", "NEST", "STUD", "SENT", "TEST", "SEND", "TENT", "TEND"],
    "MANAGER": ["MANGA", "RANGE", "AREA", "RAGE", "NAME", "EARN", "NEAR", "MEAN"],
    "ARTISTS": ["STAR", "TRI", "TAR", "RAS", "SAT", "SIR", "IST", "SIT"],
    "PARTNER": ["PART", "RATE", "RENT", "TEAR", "NEAR", "RARE", "NET", "APT"],
    "MONSTER": ["STORM", "MONTE", "TONER", "STORE", "MORES", "STEM", "MORE", "NOSE"],
    "PALACES": ["SPACE", "CAPES", "CASE", "CAPE", "PALE", "PACE", "SPEC", "SEAL"],
    "TROPHY": ["HOT", "PRO", "HOP", "TRY", "TOP", "OPT", "TOY"],
    "STORIES": ["ROSE", "SORT", "RISE", "ROSS", "REST", "TIER", "SIT", "ISO"],
    "MOUNTAIN": ["AMINO", "MOUNT", "ATOM", "MAIN", "UNIT", "AUTO", "UNTO", "ANTI"],
    "VACATION": ["COIN", "CANT", "ICON", "COAT", "CAT", "VIA", "NOT", "TIN"],
    "BIRTHDAY": ["DIRTY", "THIRD", "DAIRY", "BATH", "BRAD", "BIRD", "TRAY", "DIRT"],
    "ATTITUDE": ["IDEA", "DIET", "TED", "ATE", "TIE", "AID", "TEA", "IDE"],
    "BRILLIANT": ["TRAIN", "BALI", "ANTI", "BALL", "TALL", "BARN", "TILL", "BILL"],
    "STRENGTH": ["REST", "NEST", "TEST", "SENT", "GENS", "SET", "TEN", "SER"],
    "TREASURE": ["STAR", "SURE", "EATS", "TREE", "RATE", "EAST", "EASE", "RARE"],
    "PRESENTS": ["SENSE", "PETER", "RESET", "SEPS", "RENT", "SEPT", "SENT", "PEER"],
    "AIRPLANE": ["PLAIN", "LEARN", "PEARL", "PLANE", "ALIEN", "ARENA", "RAIL", "PARA"],
    "DESCRIBE": ["BREED", "CRIED", "RISE", "BRED", "IDES", "ICED", "ERIC", "DISC"],
    "INTERNET": ["ENTER", "TIRE", "TEEN", "RENT", "TIER", "TREE", "NINE", "TEE"],
    "EVERYDAY": ["VARY", "READ", "YEAR", "DEER", "VERY", "REED", "DEAR", "ARED"],
    "DAUGHTER": ["DAUGHTER", "GATHER", "RATED", "GATED", "ARGUE", "DEATH", "GRADE", "GUARD"],
    "SOUTHERN": ["TUNER", "STORE", "THOSE", "OUTER", "HOUSE", "OTHER", "HORSE", "SHORT"],
    "AVAILABLE": ["VILLA", "ABLE", "BALI", "BELL", "BALL", "ALA", "VIA", "ALL"],
    "ADVENTURE": ["ADVENTURE", "AVENUE", "TENDER", "NATURE", "RUNED", "NERVE", "NEVER", "RATED"],
    "BIRTHRATE": ["HEART", "THETA", "TREAT", "THEIR", "BIRTH", "EARTH", "RARE", "TEAR"],
    "BRIGHTEST": ["EIGHT", "SHIRT", "TIGHT", "SIGHT", "TRIBE", "RIGHT", "BIRTH", "TIGER"],
    "EVERGREEN": ["EVER", "EVEN", "REV", "GEN", "EVE"],
    "WONDERFUL": ["WONDER", "FOLDER", "LOWER", "NOWED", "OWNER", "WOUND", "OLDER", "WORLD"],
]
