import Foundation

// AUTO-GENERATED by tools/generate_levels.py — do not edit by hand.
// Re-run the generator to update levels.

enum Dir {
    case across
    case down
}

struct PlacedWord {
    let word: String
    let row: Int
    let col: Int
    let dir: Dir
}

struct Cell: Hashable {
    let row: Int
    let col: Int
}

struct Level {
    static let totalLevels = 100

    let rows: Int
    let cols: Int
    let letters: [Character]
    let words: [PlacedWord]

    var answersSet: Set<String> { Set(words.map { $0.word }) }

    var usedCells: Set<Cell> {
        var used = Set<Cell>()
        for pw in words {
            for i in 0..<pw.word.count {
                let cell: Cell
                switch pw.dir {
                case .across: cell = Cell(row: pw.row, col: pw.col + i)
                case .down:   cell = Cell(row: pw.row + i, col: pw.col)
                }
                used.insert(cell)
            }
        }
        return used
    }

    func solutionLetter(row: Int, col: Int) -> Character? {
        for pw in words {
            for (i, ch) in pw.word.enumerated() {
                let r: Int, c: Int
                switch pw.dir {
                case .across: r = pw.row; c = pw.col + i
                case .down:   r = pw.row + i; c = pw.col
                }
                if r == row && c == col { return ch }
            }
        }
        return nil
    }

    var bonusWords: [String] { LEVEL_BONUS[String(letters)] ?? [] }

    static func get(_ levelNum: Int) -> Level {
        let idx = max(0, min(levelNum - 1, LEVELS.count - 1))
        return LEVELS[idx]
    }
}

private let LEVELS: [Level] = [
    Level(rows: 5, cols: 5, letters: ["C", "A", "T", "S"],
          words: [PlacedWord(word: "CAST", row: 1, col: 0, dir: .across), PlacedWord(word: "CAT", row: 1, col: 0, dir: .down), PlacedWord(word: "SAT", row: 1, col: 2, dir: .down)]),
    Level(rows: 6, cols: 6, letters: ["S", "P", "I", "N", "E"],
          words: [PlacedWord(word: "SPINE", row: 1, col: 0, dir: .across), PlacedWord(word: "SIN", row: 1, col: 0, dir: .down), PlacedWord(word: "NIP", row: 1, col: 3, dir: .down), PlacedWord(word: "PEN", row: 3, col: 3, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["H", "A", "S", "T", "E"],
          words: [PlacedWord(word: "HASTE", row: 1, col: 0, dir: .across), PlacedWord(word: "HATE", row: 1, col: 0, dir: .down), PlacedWord(word: "SEAT", row: 1, col: 2, dir: .down), PlacedWord(word: "EAT", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["W", "A", "R", "M", "S"],
          words: [PlacedWord(word: "SWARM", row: 1, col: 0, dir: .across), PlacedWord(word: "SAW", row: 1, col: 0, dir: .down), PlacedWord(word: "RAM", row: 1, col: 3, dir: .down), PlacedWord(word: "WARM", row: 3, col: 0, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["C", "A", "R", "E", "S"],
          words: [PlacedWord(word: "CARES", row: 1, col: 0, dir: .across), PlacedWord(word: "CARE", row: 1, col: 0, dir: .down), PlacedWord(word: "SEAR", row: 1, col: 4, dir: .down), PlacedWord(word: "ERA", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["G", "R", "I", "N", "D", "S"],
          words: [PlacedWord(word: "GRINS", row: 1, col: 0, dir: .across), PlacedWord(word: "GIN", row: 1, col: 0, dir: .down), PlacedWord(word: "SIR", row: 1, col: 4, dir: .down), PlacedWord(word: "RID", row: 3, col: 4, dir: .across), PlacedWord(word: "DIG", row: 3, col: 6, dir: .down)]),
    Level(rows: 8, cols: 8, letters: ["P", "L", "A", "N", "E", "T", "S"],
          words: [PlacedWord(word: "PLANETS", row: 1, col: 0, dir: .across), PlacedWord(word: "PETAL", row: 1, col: 0, dir: .down), PlacedWord(word: "NETS", row: 1, col: 3, dir: .down), PlacedWord(word: "SLANT", row: 1, col: 6, dir: .down), PlacedWord(word: "ANTS", row: 4, col: 0, dir: .across)]),
    Level(rows: 8, cols: 8, letters: ["C", "R", "A", "N", "E", "S", "D"],
          words: [PlacedWord(word: "CRANES", row: 1, col: 0, dir: .across), PlacedWord(word: "CARED", row: 1, col: 0, dir: .down), PlacedWord(word: "NEARS", row: 1, col: 3, dir: .down), PlacedWord(word: "SANE", row: 1, col: 5, dir: .down), PlacedWord(word: "DENS", row: 5, col: 0, dir: .across), PlacedWord(word: "END", row: 5, col: 1, dir: .down)]),
    Level(rows: 8, cols: 8, letters: ["S", "T", "O", "R", "E", "D"],
          words: [PlacedWord(word: "STORED", row: 1, col: 0, dir: .across), PlacedWord(word: "SORT", row: 1, col: 0, dir: .down), PlacedWord(word: "REST", row: 1, col: 3, dir: .down), PlacedWord(word: "DOSE", row: 1, col: 5, dir: .down), PlacedWord(word: "ROES", row: 3, col: 0, dir: .across)]),
    Level(rows: 9, cols: 9, letters: ["T", "R", "A", "I", "N", "S", "E"],
          words: [PlacedWord(word: "TRAINS", row: 1, col: 0, dir: .across), PlacedWord(word: "TEARS", row: 1, col: 0, dir: .down), PlacedWord(word: "INSET", row: 1, col: 3, dir: .down), PlacedWord(word: "SIREN", row: 1, col: 5, dir: .down), PlacedWord(word: "ANTS", row: 3, col: 0, dir: .across), PlacedWord(word: "SENT", row: 5, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["G", "R", "A", "C", "E"],
          words: [PlacedWord(word: "RAGE", row: 2, col: 0, dir: .across), PlacedWord(word: "GRACE", row: 1, col: 0, dir: .down), PlacedWord(word: "CARE", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["D", "R", "E", "A", "M"],
          words: [PlacedWord(word: "RAMED", row: 2, col: 0, dir: .across), PlacedWord(word: "DREAM", row: 1, col: 0, dir: .down), PlacedWord(word: "ARMED", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["B", "R", "E", "A", "D"],
          words: [PlacedWord(word: "BEAR", row: 1, col: 0, dir: .across), PlacedWord(word: "BREAD", row: 1, col: 0, dir: .down), PlacedWord(word: "ABED", row: 1, col: 2, dir: .down)]),
    Level(rows: 8, cols: 4, letters: ["F", "L", "A", "M", "E"],
          words: [PlacedWord(word: "FAME", row: 2, col: 0, dir: .across), PlacedWord(word: "FLAME", row: 2, col: 0, dir: .down), PlacedWord(word: "LEAF", row: 1, col: 3, dir: .down)]),
    Level(rows: 7, cols: 4, letters: ["S", "O", "L", "I", "D"],
          words: [PlacedWord(word: "IDOL", row: 2, col: 0, dir: .across), PlacedWord(word: "SOLID", row: 1, col: 2, dir: .down), PlacedWord(word: "SOIL", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["S", "T", "O", "N", "E"],
          words: [PlacedWord(word: "NOTE", row: 2, col: 0, dir: .across), PlacedWord(word: "STONE", row: 1, col: 2, dir: .down), PlacedWord(word: "TONE", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["W", "A", "T", "E", "R"],
          words: [PlacedWord(word: "RATE", row: 2, col: 0, dir: .across), PlacedWord(word: "WATER", row: 1, col: 1, dir: .down), PlacedWord(word: "TEAR", row: 1, col: 3, dir: .down)]),
    Level(rows: 7, cols: 4, letters: ["O", "C", "E", "A", "N"],
          words: [PlacedWord(word: "ACNE", row: 2, col: 0, dir: .across), PlacedWord(word: "OCEAN", row: 1, col: 1, dir: .down), PlacedWord(word: "ONCE", row: 5, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["P", "E", "A", "C", "E"],
          words: [PlacedWord(word: "PACE", row: 1, col: 0, dir: .across), PlacedWord(word: "PEACE", row: 1, col: 0, dir: .down), PlacedWord(word: "CAPE", row: 1, col: 2, dir: .down)]),
    Level(rows: 7, cols: 5, letters: ["S", "P", "A", "C", "E"],
          words: [PlacedWord(word: "CAPES", row: 2, col: 0, dir: .across), PlacedWord(word: "SPACE", row: 1, col: 2, dir: .down), PlacedWord(word: "CASE", row: 2, col: 0, dir: .down)]),
    Level(rows: 7, cols: 6, letters: ["H", "E", "A", "R", "T"],
          words: [PlacedWord(word: "EARTH", row: 2, col: 0, dir: .across), PlacedWord(word: "HEART", row: 1, col: 0, dir: .down), PlacedWord(word: "TEAR", row: 2, col: 3, dir: .down), PlacedWord(word: "RATE", row: 4, col: 2, dir: .across)]),
    Level(rows: 8, cols: 4, letters: ["P", "L", "A", "T", "E"],
          words: [PlacedWord(word: "PALE", row: 2, col: 0, dir: .across), PlacedWord(word: "PLATE", row: 2, col: 0, dir: .down), PlacedWord(word: "TAPE", row: 5, col: 0, dir: .across), PlacedWord(word: "PET", row: 1, col: 3, dir: .down)]),
    Level(rows: 7, cols: 4, letters: ["T", "R", "A", "C", "K"],
          words: [PlacedWord(word: "CART", row: 2, col: 0, dir: .across), PlacedWord(word: "TRACK", row: 1, col: 2, dir: .down), PlacedWord(word: "RACK", row: 4, col: 0, dir: .across), PlacedWord(word: "CAR", row: 2, col: 0, dir: .down)]),
    Level(rows: 8, cols: 4, letters: ["S", "C", "A", "L", "E"],
          words: [PlacedWord(word: "SEAL", row: 2, col: 0, dir: .across), PlacedWord(word: "SCALE", row: 2, col: 0, dir: .down), PlacedWord(word: "CASE", row: 1, col: 2, dir: .down), PlacedWord(word: "ACE", row: 4, col: 0, dir: .across)]),
    Level(rows: 7, cols: 4, letters: ["P", "R", "I", "N", "T"],
          words: [PlacedWord(word: "TRIP", row: 2, col: 0, dir: .across), PlacedWord(word: "PRINT", row: 1, col: 1, dir: .down), PlacedWord(word: "TIN", row: 5, col: 1, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["C", "R", "A", "F", "T"],
          words: [PlacedWord(word: "FACT", row: 1, col: 0, dir: .across), PlacedWord(word: "CRAFT", row: 1, col: 2, dir: .down), PlacedWord(word: "CART", row: 3, col: 1, dir: .across), PlacedWord(word: "ART", row: 5, col: 0, dir: .across)]),
    Level(rows: 7, cols: 5, letters: ["S", "M", "I", "L", "E"],
          words: [PlacedWord(word: "LIMES", row: 2, col: 0, dir: .across), PlacedWord(word: "SMILE", row: 1, col: 2, dir: .down), PlacedWord(word: "MILE", row: 4, col: 0, dir: .across), PlacedWord(word: "SLIM", row: 1, col: 0, dir: .down)]),
    Level(rows: 7, cols: 4, letters: ["F", "R", "O", "S", "T"],
          words: [PlacedWord(word: "SOFT", row: 1, col: 0, dir: .across), PlacedWord(word: "FROST", row: 1, col: 2, dir: .down), PlacedWord(word: "SORT", row: 1, col: 0, dir: .down)]),
    Level(rows: 8, cols: 4, letters: ["B", "R", "A", "V", "E"],
          words: [PlacedWord(word: "BEAR", row: 2, col: 0, dir: .across), PlacedWord(word: "BRAVE", row: 2, col: 0, dir: .down), PlacedWord(word: "BARE", row: 1, col: 2, dir: .down), PlacedWord(word: "ARE", row: 4, col: 0, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["Q", "U", "I", "E", "T"],
          words: [PlacedWord(word: "QUITE", row: 2, col: 0, dir: .across), PlacedWord(word: "QUIET", row: 2, col: 0, dir: .down), PlacedWord(word: "TIE", row: 1, col: 2, dir: .down), PlacedWord(word: "TUE", row: 6, col: 0, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["P", "L", "A", "T", "E", "S"],
          words: [PlacedWord(word: "PLATE", row: 2, col: 0, dir: .across), PlacedWord(word: "PASTE", row: 2, col: 0, dir: .down), PlacedWord(word: "LEAST", row: 1, col: 4, dir: .down), PlacedWord(word: "TALES", row: 1, col: 2, dir: .down)]),
    Level(rows: 8, cols: 6, letters: ["S", "T", "R", "E", "A", "M"],
          words: [PlacedWord(word: "MASTER", row: 1, col: 0, dir: .across), PlacedWord(word: "STREAM", row: 1, col: 2, dir: .down), PlacedWord(word: "STEAM", row: 4, col: 0, dir: .across), PlacedWord(word: "SMART", row: 6, col: 1, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["B", "R", "I", "G", "H", "T"],
          words: [PlacedWord(word: "RIGHT", row: 2, col: 0, dir: .across), PlacedWord(word: "BRIGHT", row: 1, col: 0, dir: .down), PlacedWord(word: "HIT", row: 2, col: 3, dir: .down)]),
    Level(rows: 9, cols: 6, letters: ["F", "O", "R", "E", "S", "T"],
          words: [PlacedWord(word: "FOSTER", row: 2, col: 0, dir: .across), PlacedWord(word: "FOREST", row: 2, col: 0, dir: .down), PlacedWord(word: "FROST", row: 1, col: 5, dir: .down), PlacedWord(word: "STORE", row: 2, col: 2, dir: .down)]),
    Level(rows: 9, cols: 7, letters: ["G", "A", "R", "D", "E", "N"],
          words: [PlacedWord(word: "RANGED", row: 2, col: 0, dir: .across), PlacedWord(word: "DANGER", row: 1, col: 1, dir: .down), PlacedWord(word: "GARDEN", row: 2, col: 3, dir: .down), PlacedWord(word: "ANGER", row: 7, col: 2, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["C", "A", "S", "T", "L", "E"],
          words: [PlacedWord(word: "TALES", row: 2, col: 0, dir: .across), PlacedWord(word: "CASTLE", row: 1, col: 1, dir: .down), PlacedWord(word: "LEAST", row: 1, col: 3, dir: .down), PlacedWord(word: "SEAL", row: 4, col: 3, dir: .across)]),
    Level(rows: 7, cols: 6, letters: ["I", "S", "L", "A", "N", "D"],
          words: [PlacedWord(word: "NAIL", row: 2, col: 0, dir: .across), PlacedWord(word: "SAND", row: 1, col: 1, dir: .down), PlacedWord(word: "LAND", row: 2, col: 3, dir: .down), PlacedWord(word: "AID", row: 3, col: 3, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["B", "R", "I", "D", "G", "E"],
          words: [PlacedWord(word: "RIDGE", row: 2, col: 0, dir: .across), PlacedWord(word: "BRIDGE", row: 1, col: 0, dir: .down), PlacedWord(word: "GRID", row: 2, col: 3, dir: .down), PlacedWord(word: "RIDE", row: 4, col: 2, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["D", "E", "S", "E", "R", "T"],
          words: [PlacedWord(word: "TREED", row: 2, col: 0, dir: .across), PlacedWord(word: "DESERT", row: 1, col: 2, dir: .down), PlacedWord(word: "RESET", row: 4, col: 1, dir: .across), PlacedWord(word: "TREE", row: 6, col: 2, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["P", "L", "A", "N", "E", "T"],
          words: [PlacedWord(word: "PLANT", row: 2, col: 0, dir: .across), PlacedWord(word: "PLANET", row: 2, col: 0, dir: .down), PlacedWord(word: "PANEL", row: 1, col: 2, dir: .down), PlacedWord(word: "LATE", row: 5, col: 2, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["W", "I", "N", "T", "E", "R"],
          words: [PlacedWord(word: "INTER", row: 2, col: 0, dir: .across), PlacedWord(word: "WINTER", row: 1, col: 0, dir: .down), PlacedWord(word: "WRITE", row: 1, col: 4, dir: .down), PlacedWord(word: "TIER", row: 2, col: 2, dir: .down), PlacedWord(word: "TIE", row: 4, col: 0, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["S", "P", "R", "I", "N", "G"],
          words: [PlacedWord(word: "GRIP", row: 2, col: 0, dir: .across), PlacedWord(word: "SPRING", row: 1, col: 3, dir: .down), PlacedWord(word: "SPIN", row: 4, col: 1, dir: .across), PlacedWord(word: "PING", row: 6, col: 0, dir: .across), PlacedWord(word: "SIR", row: 1, col: 3, dir: .across)]),
    Level(rows: 9, cols: 5, letters: ["S", "U", "M", "M", "E", "R"],
          words: [PlacedWord(word: "SERUM", row: 2, col: 0, dir: .across), PlacedWord(word: "SUMMER", row: 2, col: 0, dir: .down), PlacedWord(word: "SURE", row: 1, col: 3, dir: .down), PlacedWord(word: "ERS", row: 6, col: 0, dir: .across), PlacedWord(word: "SER", row: 4, col: 2, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["M", "O", "T", "H", "E", "R"],
          words: [PlacedWord(word: "OTHER", row: 2, col: 0, dir: .across), PlacedWord(word: "MOTHER", row: 1, col: 0, dir: .down), PlacedWord(word: "THEM", row: 1, col: 2, dir: .down), PlacedWord(word: "MORE", row: 4, col: 2, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["F", "A", "T", "H", "E", "R"],
          words: [PlacedWord(word: "EARTH", row: 2, col: 0, dir: .across), PlacedWord(word: "FATHER", row: 1, col: 1, dir: .down), PlacedWord(word: "HEART", row: 2, col: 4, dir: .down), PlacedWord(word: "HART", row: 4, col: 3, dir: .across), PlacedWord(word: "REF", row: 5, col: 0, dir: .across)]),
    Level(rows: 9, cols: 8, letters: ["T", "E", "A", "C", "H", "E", "R"],
          words: [PlacedWord(word: "HEATER", row: 2, col: 0, dir: .across), PlacedWord(word: "TEACHER", row: 1, col: 1, dir: .down), PlacedWord(word: "CREATE", row: 1, col: 5, dir: .down), PlacedWord(word: "THREE", row: 2, col: 3, dir: .down), PlacedWord(word: "REACH", row: 4, col: 3, dir: .across)]),
    Level(rows: 8, cols: 4, letters: ["D", "O", "C", "T", "O", "R"],
          words: [PlacedWord(word: "ROOT", row: 2, col: 0, dir: .across), PlacedWord(word: "DOCTOR", row: 1, col: 1, dir: .down), PlacedWord(word: "CORD", row: 5, col: 0, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["W", "O", "N", "D", "E", "R"],
          words: [PlacedWord(word: "OWNER", row: 2, col: 0, dir: .across), PlacedWord(word: "WONDER", row: 1, col: 0, dir: .down), PlacedWord(word: "ROWED", row: 2, col: 4, dir: .down), PlacedWord(word: "DOWN", row: 4, col: 2, dir: .across), PlacedWord(word: "NODE", row: 2, col: 2, dir: .down)]),
    Level(rows: 9, cols: 6, letters: ["M", "A", "R", "K", "E", "T"],
          words: [PlacedWord(word: "MAKER", row: 2, col: 0, dir: .across), PlacedWord(word: "MARKET", row: 2, col: 0, dir: .down), PlacedWord(word: "META", row: 1, col: 3, dir: .down), PlacedWord(word: "TERM", row: 7, col: 0, dir: .across), PlacedWord(word: "MAKE", row: 4, col: 2, dir: .across)]),
    Level(rows: 8, cols: 5, letters: ["B", "U", "T", "T", "E", "R"],
          words: [PlacedWord(word: "TRUE", row: 2, col: 0, dir: .across), PlacedWord(word: "BUTTER", row: 1, col: 2, dir: .down), PlacedWord(word: "TUBE", row: 2, col: 0, dir: .down), PlacedWord(word: "TUE", row: 4, col: 2, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["C", "O", "T", "T", "A", "G", "E"],
          words: [PlacedWord(word: "COTTAGE", row: 2, col: 0, dir: .across), PlacedWord(word: "COAT", row: 2, col: 0, dir: .down), PlacedWord(word: "CAGE", row: 1, col: 4, dir: .down), PlacedWord(word: "GET", row: 1, col: 6, dir: .down), PlacedWord(word: "TOE", row: 2, col: 2, dir: .down)]),
    Level(rows: 8, cols: 8, letters: ["T", "E", "N", "D", "E", "R"],
          words: [PlacedWord(word: "RENTED", row: 2, col: 0, dir: .across), PlacedWord(word: "TENDER", row: 1, col: 1, dir: .down), PlacedWord(word: "TREED", row: 2, col: 3, dir: .down), PlacedWord(word: "ENTER", row: 4, col: 3, dir: .across), PlacedWord(word: "DEER", row: 6, col: 3, dir: .across)]),
    Level(rows: 8, cols: 8, letters: ["M", "A", "S", "T", "E", "R"],
          words: [PlacedWord(word: "STREAM", row: 2, col: 0, dir: .across), PlacedWord(word: "MASTER", row: 1, col: 4, dir: .down), PlacedWord(word: "SMART", row: 2, col: 0, dir: .down), PlacedWord(word: "STEAM", row: 4, col: 3, dir: .across), PlacedWord(word: "MART", row: 6, col: 2, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["P", "O", "S", "T", "E", "R"],
          words: [PlacedWord(word: "STORE", row: 2, col: 0, dir: .across), PlacedWord(word: "POSTER", row: 1, col: 2, dir: .down), PlacedWord(word: "SPORT", row: 2, col: 0, dir: .down), PlacedWord(word: "ROPES", row: 6, col: 2, dir: .across), PlacedWord(word: "REPS", row: 1, col: 4, dir: .down)]),
    Level(rows: 8, cols: 7, letters: ["T", "R", "A", "V", "E", "L"],
          words: [PlacedWord(word: "ALERT", row: 2, col: 0, dir: .across), PlacedWord(word: "TRAVEL", row: 1, col: 3, dir: .down), PlacedWord(word: "ALTER", row: 2, col: 0, dir: .down), PlacedWord(word: "LATE", row: 6, col: 3, dir: .across), PlacedWord(word: "VAT", row: 4, col: 3, dir: .across)]),
    Level(rows: 9, cols: 7, letters: ["M", "O", "R", "N", "I", "N", "G"],
          words: [PlacedWord(word: "MINOR", row: 2, col: 0, dir: .across), PlacedWord(word: "MORNING", row: 1, col: 3, dir: .down), PlacedWord(word: "NORM", row: 4, col: 3, dir: .across), PlacedWord(word: "RING", row: 1, col: 1, dir: .down), PlacedWord(word: "IRON", row: 6, col: 0, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["E", "V", "E", "N", "I", "N", "G"],
          words: [PlacedWord(word: "ENGINE", row: 1, col: 0, dir: .across), PlacedWord(word: "EVENING", row: 1, col: 0, dir: .down), PlacedWord(word: "GIVEN", row: 1, col: 2, dir: .down), PlacedWord(word: "NINE", row: 1, col: 4, dir: .down), PlacedWord(word: "EVEN", row: 4, col: 2, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["P", "I", "C", "T", "U", "R", "E"],
          words: [PlacedWord(word: "PRICE", row: 2, col: 0, dir: .across), PlacedWord(word: "PICTURE", row: 1, col: 2, dir: .down), PlacedWord(word: "TRIP", row: 4, col: 2, dir: .across), PlacedWord(word: "TIER", row: 7, col: 0, dir: .across), PlacedWord(word: "PURE", row: 2, col: 0, dir: .down)]),
    Level(rows: 9, cols: 6, letters: ["W", "E", "A", "T", "H", "E", "R"],
          words: [PlacedWord(word: "HEATER", row: 2, col: 0, dir: .across), PlacedWord(word: "WEATHER", row: 1, col: 1, dir: .down), PlacedWord(word: "WHERE", row: 5, col: 0, dir: .across), PlacedWord(word: "THERE", row: 2, col: 3, dir: .down), PlacedWord(word: "TREE", row: 1, col: 5, dir: .down)]),
    Level(rows: 9, cols: 5, letters: ["J", "O", "U", "R", "N", "E", "Y"],
          words: [PlacedWord(word: "ENJOY", row: 2, col: 0, dir: .across), PlacedWord(word: "JOURNEY", row: 1, col: 3, dir: .down), PlacedWord(word: "YOUR", row: 4, col: 0, dir: .across), PlacedWord(word: "JURY", row: 7, col: 0, dir: .across), PlacedWord(word: "NEO", row: 2, col: 1, dir: .down)]),
    Level(rows: 7, cols: 9, letters: ["M", "E", "E", "T", "I", "N", "G"],
          words: [PlacedWord(word: "MEETING", row: 2, col: 0, dir: .across), PlacedWord(word: "ITEM", row: 1, col: 3, dir: .down), PlacedWord(word: "MINT", row: 2, col: 0, dir: .down), PlacedWord(word: "GENE", row: 2, col: 6, dir: .down), PlacedWord(word: "MEET", row: 5, col: 5, dir: .across), PlacedWord(word: "TIE", row: 5, col: 0, dir: .across)]),
    Level(rows: 10, cols: 7, letters: ["R", "E", "A", "D", "I", "N", "G"],
          words: [PlacedWord(word: "GRAINED", row: 2, col: 0, dir: .across), PlacedWord(word: "READING", row: 2, col: 1, dir: .down), PlacedWord(word: "DANGER", row: 2, col: 6, dir: .down), PlacedWord(word: "RINGED", row: 1, col: 3, dir: .down), PlacedWord(word: "GRAIN", row: 8, col: 1, dir: .across), PlacedWord(word: "RANGE", row: 4, col: 0, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["W", "A", "L", "K", "I", "N", "G"],
          words: [PlacedWord(word: "WAKING", row: 2, col: 0, dir: .across), PlacedWord(word: "WALKING", row: 2, col: 0, dir: .down), PlacedWord(word: "LING", row: 1, col: 3, dir: .down), PlacedWord(word: "NAIL", row: 7, col: 0, dir: .across), PlacedWord(word: "GAIN", row: 2, col: 5, dir: .down), PlacedWord(word: "INK", row: 4, col: 5, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["F", "O", "R", "E", "V", "E", "R"],
          words: [PlacedWord(word: "REFER", row: 2, col: 0, dir: .across), PlacedWord(word: "FEVER", row: 1, col: 1, dir: .down), PlacedWord(word: "ROVER", row: 2, col: 4, dir: .down), PlacedWord(word: "REEF", row: 5, col: 3, dir: .across), PlacedWord(word: "FEE", row: 4, col: 0, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["F", "R", "E", "E", "D", "O", "M"],
          words: [PlacedWord(word: "FORMED", row: 2, col: 0, dir: .across), PlacedWord(word: "FREEDOM", row: 2, col: 0, dir: .down), PlacedWord(word: "FREED", row: 1, col: 2, dir: .down), PlacedWord(word: "REEF", row: 1, col: 4, dir: .down), PlacedWord(word: "FORD", row: 4, col: 4, dir: .across), PlacedWord(word: "MERE", row: 8, col: 0, dir: .across)]),
    Level(rows: 9, cols: 7, letters: ["S", "T", "A", "T", "I", "O", "N"],
          words: [PlacedWord(word: "SATIN", row: 2, col: 0, dir: .across), PlacedWord(word: "STATION", row: 1, col: 2, dir: .down), PlacedWord(word: "SAINT", row: 2, col: 0, dir: .down), PlacedWord(word: "ANTI", row: 1, col: 4, dir: .down), PlacedWord(word: "INTO", row: 7, col: 1, dir: .across), PlacedWord(word: "ION", row: 4, col: 4, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["V", "I", "C", "T", "O", "R", "Y"],
          words: [PlacedWord(word: "VICTOR", row: 1, col: 0, dir: .across), PlacedWord(word: "VICTORY", row: 1, col: 0, dir: .down), PlacedWord(word: "TRIO", row: 1, col: 3, dir: .down), PlacedWord(word: "CITY", row: 3, col: 2, dir: .across)]),
    Level(rows: 6, cols: 8, letters: ["M", "Y", "S", "T", "E", "R", "Y"],
          words: [PlacedWord(word: "MYSTERY", row: 1, col: 0, dir: .across), PlacedWord(word: "TERM", row: 1, col: 3, dir: .down), PlacedWord(word: "REST", row: 1, col: 5, dir: .down), PlacedWord(word: "STEM", row: 4, col: 0, dir: .across), PlacedWord(word: "SET", row: 3, col: 5, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["H", "I", "S", "T", "O", "R", "Y"],
          words: [PlacedWord(word: "SHIRT", row: 2, col: 0, dir: .across), PlacedWord(word: "HISTORY", row: 1, col: 2, dir: .down), PlacedWord(word: "STORY", row: 2, col: 0, dir: .down), PlacedWord(word: "THIS", row: 2, col: 4, dir: .down), PlacedWord(word: "TRIO", row: 4, col: 2, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["F", "A", "C", "T", "O", "R", "Y"],
          words: [PlacedWord(word: "FACTOR", row: 2, col: 0, dir: .across), PlacedWord(word: "FACTORY", row: 2, col: 0, dir: .down), PlacedWord(word: "ACTOR", row: 1, col: 2, dir: .down), PlacedWord(word: "CRAFT", row: 1, col: 5, dir: .down), PlacedWord(word: "CAR", row: 1, col: 5, dir: .across), PlacedWord(word: "FAR", row: 4, col: 5, dir: .across)]),
    Level(rows: 10, cols: 9, letters: ["G", "A", "L", "L", "E", "R", "Y"],
          words: [PlacedWord(word: "ALLERGY", row: 2, col: 0, dir: .across), PlacedWord(word: "GALLERY", row: 1, col: 0, dir: .down), PlacedWord(word: "LARGELY", row: 2, col: 2, dir: .down), PlacedWord(word: "REALLY", row: 2, col: 4, dir: .down), PlacedWord(word: "LEGAL", row: 5, col: 4, dir: .across), PlacedWord(word: "LAYER", row: 7, col: 2, dir: .across)]),
    Level(rows: 9, cols: 6, letters: ["S", "T", "U", "D", "E", "N", "T"],
          words: [PlacedWord(word: "TUNED", row: 2, col: 0, dir: .across), PlacedWord(word: "STUDENT", row: 1, col: 0, dir: .down), PlacedWord(word: "NEST", row: 2, col: 2, dir: .down), PlacedWord(word: "TEST", row: 7, col: 0, dir: .across), PlacedWord(word: "SNED", row: 4, col: 2, dir: .across), PlacedWord(word: "DUE", row: 2, col: 4, dir: .down)]),
    Level(rows: 9, cols: 6, letters: ["T", "E", "A", "C", "H", "E", "R"],
          words: [PlacedWord(word: "CREATE", row: 2, col: 0, dir: .across), PlacedWord(word: "TEACHER", row: 1, col: 2, dir: .down), PlacedWord(word: "HEATER", row: 1, col: 5, dir: .down), PlacedWord(word: "THREE", row: 5, col: 1, dir: .across), PlacedWord(word: "EARTH", row: 7, col: 0, dir: .across), PlacedWord(word: "ACRE", row: 1, col: 0, dir: .down)]),
    Level(rows: 10, cols: 8, letters: ["M", "A", "N", "A", "G", "E", "R"],
          words: [PlacedWord(word: "MANAGE", row: 2, col: 0, dir: .across), PlacedWord(word: "MANAGER", row: 2, col: 0, dir: .down), PlacedWord(word: "GERMAN", row: 2, col: 4, dir: .down), PlacedWord(word: "MANGA", row: 6, col: 3, dir: .across), PlacedWord(word: "ANGER", row: 1, col: 2, dir: .down), PlacedWord(word: "RAGE", row: 8, col: 0, dir: .across)]),
    Level(rows: 7, cols: 7, letters: ["A", "R", "T", "I", "S", "T", "S"],
          words: [PlacedWord(word: "ARTIST", row: 2, col: 0, dir: .across), PlacedWord(word: "START", row: 1, col: 2, dir: .down), PlacedWord(word: "STAR", row: 2, col: 4, dir: .down), PlacedWord(word: "TARS", row: 1, col: 0, dir: .down), PlacedWord(word: "SIR", row: 4, col: 0, dir: .across), PlacedWord(word: "RAT", row: 5, col: 4, dir: .across)]),
    Level(rows: 9, cols: 8, letters: ["P", "A", "R", "T", "N", "E", "R"],
          words: [PlacedWord(word: "PARENT", row: 1, col: 0, dir: .across), PlacedWord(word: "PARTNER", row: 1, col: 0, dir: .down), PlacedWord(word: "RARE", row: 1, col: 2, dir: .down), PlacedWord(word: "RENT", row: 7, col: 0, dir: .across), PlacedWord(word: "TEAR", row: 1, col: 5, dir: .down), PlacedWord(word: "TAPE", row: 3, col: 4, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["M", "O", "N", "S", "T", "E", "R"],
          words: [PlacedWord(word: "MENTOR", row: 2, col: 0, dir: .across), PlacedWord(word: "MONSTER", row: 2, col: 0, dir: .down), PlacedWord(word: "STORM", row: 1, col: 3, dir: .down), PlacedWord(word: "MONTE", row: 5, col: 3, dir: .across), PlacedWord(word: "REST", row: 8, col: 0, dir: .across), PlacedWord(word: "TOE", row: 6, col: 0, dir: .across)]),
    Level(rows: 8, cols: 7, letters: ["P", "A", "L", "A", "C", "E", "S"],
          words: [PlacedWord(word: "PALACE", row: 2, col: 0, dir: .across), PlacedWord(word: "PLACE", row: 2, col: 0, dir: .down), PlacedWord(word: "SCALE", row: 1, col: 4, dir: .down), PlacedWord(word: "SEAL", row: 5, col: 3, dir: .across), PlacedWord(word: "ALAS", row: 1, col: 2, dir: .down)]),
    Level(rows: 6, cols: 6, letters: ["T", "R", "O", "P", "H", "Y"],
          words: [PlacedWord(word: "PORT", row: 2, col: 0, dir: .across), PlacedWord(word: "THY", row: 2, col: 3, dir: .down), PlacedWord(word: "HOP", row: 1, col: 1, dir: .down), PlacedWord(word: "HOT", row: 3, col: 3, dir: .across)]),
    Level(rows: 8, cols: 8, letters: ["S", "T", "O", "R", "I", "E", "S"],
          words: [PlacedWord(word: "SISTER", row: 2, col: 0, dir: .across), PlacedWord(word: "RESIST", row: 1, col: 4, dir: .down), PlacedWord(word: "STORE", row: 2, col: 0, dir: .down), PlacedWord(word: "TIRE", row: 4, col: 3, dir: .across), PlacedWord(word: "TIER", row: 6, col: 4, dir: .across), PlacedWord(word: "ESS", row: 1, col: 2, dir: .down)]),
    Level(rows: 10, cols: 8, letters: ["M", "O", "U", "N", "T", "A", "I", "N"],
          words: [PlacedWord(word: "NATION", row: 2, col: 0, dir: .across), PlacedWord(word: "MOUNTAIN", row: 1, col: 4, dir: .down), PlacedWord(word: "AMOUNT", row: 2, col: 1, dir: .down), PlacedWord(word: "UNION", row: 4, col: 3, dir: .across), PlacedWord(word: "ANTI", row: 6, col: 4, dir: .across), PlacedWord(word: "MINT", row: 8, col: 2, dir: .across), PlacedWord(word: "OUT", row: 5, col: 0, dir: .across)]),
    Level(rows: 10, cols: 9, letters: ["O", "B", "S", "E", "R", "V", "E", "R"],
          words: [PlacedWord(word: "OBSERVE", row: 1, col: 0, dir: .across), PlacedWord(word: "OBSERVER", row: 1, col: 0, dir: .down), PlacedWord(word: "SERVER", row: 1, col: 2, dir: .down), PlacedWord(word: "VERSE", row: 1, col: 5, dir: .down), PlacedWord(word: "ROVER", row: 8, col: 0, dir: .across), PlacedWord(word: "SERVE", row: 5, col: 4, dir: .across), PlacedWord(word: "ROSE", row: 3, col: 5, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["B", "I", "R", "T", "H", "D", "A", "Y"],
          words: [PlacedWord(word: "HYBRID", row: 2, col: 0, dir: .across), PlacedWord(word: "BIRTHDAY", row: 1, col: 4, dir: .down), PlacedWord(word: "THIRD", row: 1, col: 0, dir: .down), PlacedWord(word: "HAIRY", row: 7, col: 3, dir: .across), PlacedWord(word: "BIRTH", row: 2, col: 2, dir: .down), PlacedWord(word: "HARD", row: 5, col: 4, dir: .across), PlacedWord(word: "RAT", row: 4, col: 2, dir: .across)]),
    Level(rows: 7, cols: 10, letters: ["A", "T", "T", "I", "T", "U", "D", "E"],
          words: [PlacedWord(word: "ATTITUDE", row: 1, col: 0, dir: .across), PlacedWord(word: "AUDIT", row: 1, col: 0, dir: .down), PlacedWord(word: "DATE", row: 1, col: 6, dir: .down), PlacedWord(word: "TIDE", row: 1, col: 2, dir: .down), PlacedWord(word: "EDIT", row: 4, col: 6, dir: .across), PlacedWord(word: "TIED", row: 1, col: 4, dir: .down), PlacedWord(word: "DIE", row: 3, col: 2, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["P", "A", "R", "E", "N", "T", "A", "L"],
          words: [PlacedWord(word: "RENTAL", row: 2, col: 0, dir: .across), PlacedWord(word: "PARENTAL", row: 1, col: 4, dir: .down), PlacedWord(word: "PARENT", row: 4, col: 1, dir: .across), PlacedWord(word: "PLANET", row: 7, col: 2, dir: .across), PlacedWord(word: "NEAR", row: 2, col: 2, dir: .down), PlacedWord(word: "ART", row: 1, col: 0, dir: .down)]),
    Level(rows: 7, cols: 9, letters: ["S", "T", "R", "E", "N", "G", "T", "H"],
          words: [PlacedWord(word: "STRENGTH", row: 2, col: 0, dir: .across), PlacedWord(word: "TENT", row: 2, col: 1, dir: .down), PlacedWord(word: "THEN", row: 2, col: 6, dir: .down), PlacedWord(word: "NEST", row: 1, col: 3, dir: .down), PlacedWord(word: "HERS", row: 4, col: 5, dir: .across), PlacedWord(word: "NET", row: 4, col: 1, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["T", "R", "E", "A", "S", "U", "R", "E"],
          words: [PlacedWord(word: "ARREST", row: 2, col: 0, dir: .across), PlacedWord(word: "TREASURE", row: 1, col: 1, dir: .down), PlacedWord(word: "EASTER", row: 2, col: 3, dir: .down), PlacedWord(word: "RESET", row: 7, col: 3, dir: .across), PlacedWord(word: "TARS", row: 2, col: 5, dir: .down), PlacedWord(word: "EATS", row: 4, col: 0, dir: .across), PlacedWord(word: "SURE", row: 6, col: 0, dir: .across)]),
    Level(rows: 9, cols: 9, letters: ["S", "T", "A", "R", "T", "E", "R", "S"],
          words: [PlacedWord(word: "STARTER", row: 2, col: 0, dir: .across), PlacedWord(word: "ARREST", row: 2, col: 2, dir: .down), PlacedWord(word: "TREAT", row: 2, col: 4, dir: .down), PlacedWord(word: "START", row: 2, col: 0, dir: .down), PlacedWord(word: "ASSET", row: 5, col: 4, dir: .across), PlacedWord(word: "SET", row: 6, col: 2, dir: .across), PlacedWord(word: "ERA", row: 1, col: 6, dir: .down)]),
    Level(rows: 10, cols: 7, letters: ["E", "L", "E", "C", "T", "I", "O", "N"],
          words: [PlacedWord(word: "CLIENT", row: 2, col: 0, dir: .across), PlacedWord(word: "ELECTION", row: 1, col: 1, dir: .down), PlacedWord(word: "NOTICE", row: 2, col: 4, dir: .down), PlacedWord(word: "LITE", row: 5, col: 3, dir: .across), PlacedWord(word: "ONCE", row: 7, col: 1, dir: .across), PlacedWord(word: "ICE", row: 4, col: 0, dir: .across)]),
    Level(rows: 10, cols: 9, letters: ["M", "A", "G", "A", "Z", "I", "N", "E"],
          words: [PlacedWord(word: "AMAZING", row: 2, col: 0, dir: .across), PlacedWord(word: "MAGAZINE", row: 1, col: 0, dir: .down), PlacedWord(word: "MANAGE", row: 1, col: 2, dir: .down), PlacedWord(word: "ANIME", row: 1, col: 5, dir: .down), PlacedWord(word: "IMAGE", row: 4, col: 4, dir: .across), PlacedWord(word: "ANA", row: 4, col: 0, dir: .across)]),
    Level(rows: 8, cols: 6, letters: ["I", "N", "T", "E", "R", "N", "E", "T"],
          words: [PlacedWord(word: "INTENT", row: 2, col: 0, dir: .across), PlacedWord(word: "ENTIRE", row: 1, col: 1, dir: .down), PlacedWord(word: "INNER", row: 1, col: 4, dir: .down), PlacedWord(word: "INTER", row: 4, col: 1, dir: .across), PlacedWord(word: "RENT", row: 6, col: 0, dir: .across)]),
    Level(rows: 8, cols: 10, letters: ["E", "V", "E", "R", "Y", "D", "A", "Y"],
          words: [PlacedWord(word: "EVERYDAY", row: 2, col: 0, dir: .across), PlacedWord(word: "EARED", row: 2, col: 0, dir: .down), PlacedWord(word: "EVERY", row: 2, col: 2, dir: .down), PlacedWord(word: "READY", row: 5, col: 2, dir: .across), PlacedWord(word: "EYED", row: 1, col: 7, dir: .down), PlacedWord(word: "DEE", row: 4, col: 7, dir: .across), PlacedWord(word: "AYE", row: 1, col: 4, dir: .down)]),
    Level(rows: 10, cols: 8, letters: ["D", "A", "U", "G", "H", "T", "E", "R"],
          words: [PlacedWord(word: "GATHER", row: 2, col: 0, dir: .across), PlacedWord(word: "DAUGHTER", row: 1, col: 1, dir: .down), PlacedWord(word: "THREAD", row: 1, col: 3, dir: .down), PlacedWord(word: "GRADE", row: 1, col: 5, dir: .down), PlacedWord(word: "GREAT", row: 8, col: 0, dir: .across), PlacedWord(word: "AGED", row: 5, col: 3, dir: .across), PlacedWord(word: "AGE", row: 3, col: 5, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["S", "O", "U", "T", "H", "E", "R", "N"],
          words: [PlacedWord(word: "HONEST", row: 2, col: 0, dir: .across), PlacedWord(word: "SOUTHERN", row: 1, col: 1, dir: .down), PlacedWord(word: "NORTH", row: 8, col: 1, dir: .across), PlacedWord(word: "TURNS", row: 2, col: 5, dir: .down), PlacedWord(word: "HORSE", row: 4, col: 3, dir: .across), PlacedWord(word: "REST", row: 6, col: 0, dir: .across), PlacedWord(word: "SHE", row: 6, col: 5, dir: .across)]),
    Level(rows: 10, cols: 9, letters: ["D", "E", "S", "I", "G", "N", "E", "R"],
          words: [PlacedWord(word: "REEDING", row: 2, col: 0, dir: .across), PlacedWord(word: "DESIGNER", row: 1, col: 1, dir: .down), PlacedWord(word: "RESING", row: 7, col: 0, dir: .across), PlacedWord(word: "GENDER", row: 5, col: 1, dir: .across), PlacedWord(word: "GENRE", row: 2, col: 6, dir: .down), PlacedWord(word: "RID", row: 1, col: 4, dir: .down), PlacedWord(word: "END", row: 3, col: 6, dir: .across)]),
    Level(rows: 10, cols: 8, letters: ["A", "D", "V", "E", "N", "T", "U", "R", "E"],
          words: [PlacedWord(word: "VENTURE", row: 2, col: 0, dir: .across), PlacedWord(word: "VETERAN", row: 2, col: 0, dir: .down), PlacedWord(word: "NATURE", row: 2, col: 2, dir: .down), PlacedWord(word: "TURNED", row: 1, col: 4, dir: .down), PlacedWord(word: "TENDER", row: 1, col: 6, dir: .down), PlacedWord(word: "TUNED", row: 4, col: 2, dir: .across), PlacedWord(word: "DARE", row: 6, col: 4, dir: .across)]),
    Level(rows: 11, cols: 9, letters: ["S", "T", "A", "T", "E", "M", "E", "N", "T"],
          words: [PlacedWord(word: "TESTAMENT", row: 2, col: 0, dir: .across), PlacedWord(word: "STATEMENT", row: 1, col: 0, dir: .down), PlacedWord(word: "SENATE", row: 2, col: 2, dir: .down), PlacedWord(word: "ESTATE", row: 2, col: 6, dir: .down), PlacedWord(word: "MEANT", row: 5, col: 4, dir: .across), PlacedWord(word: "TASTE", row: 2, col: 8, dir: .down), PlacedWord(word: "TEENS", row: 9, col: 0, dir: .across)]),
    Level(rows: 9, cols: 7, letters: ["B", "R", "I", "G", "H", "T", "E", "S", "T"],
          words: [PlacedWord(word: "THEIRS", row: 2, col: 0, dir: .across), PlacedWord(word: "TIGHTS", row: 2, col: 0, dir: .down), PlacedWord(word: "BRIGHT", row: 1, col: 4, dir: .down), PlacedWord(word: "TIGHT", row: 6, col: 0, dir: .across), PlacedWord(word: "RIGHT", row: 4, col: 2, dir: .across)]),
    Level(rows: 8, cols: 9, letters: ["E", "V", "E", "R", "G", "R", "E", "E", "N"],
          words: [PlacedWord(word: "REVENGE", row: 2, col: 0, dir: .across), PlacedWord(word: "NERVE", row: 1, col: 1, dir: .down), PlacedWord(word: "NEVER", row: 1, col: 3, dir: .down), PlacedWord(word: "GENRE", row: 2, col: 5, dir: .down), PlacedWord(word: "EVER", row: 6, col: 5, dir: .across)]),
    Level(rows: 11, cols: 7, letters: ["W", "O", "N", "D", "E", "R", "F", "U", "L"],
          words: [PlacedWord(word: "FOUNDER", row: 2, col: 0, dir: .across), PlacedWord(word: "WONDERFUL", row: 1, col: 1, dir: .down), PlacedWord(word: "FLOWER", row: 7, col: 1, dir: .across), PlacedWord(word: "REFUND", row: 5, col: 0, dir: .across), PlacedWord(word: "OLDER", row: 9, col: 0, dir: .across), PlacedWord(word: "DREW", row: 1, col: 6, dir: .down), PlacedWord(word: "DOWN", row: 2, col: 4, dir: .down)]),
]

private let LEVEL_BONUS: [String: [String]] = [
    "CATS": ["ACT", "ACTS", "SCAT", "CATS"],
    "SPINE": ["PIN", "PIE", "SIP", "SNIP", "PIES", "PENS", "SINE", "PINE"],
    "HASTE": ["HEAT", "SET", "HAT", "TEA", "ATE", "ETA", "EAST", "EATS"],
    "WARMS": ["WARMS", "WARS", "ARMS", "MARS", "ARM", "MAR", "RAW", "WAR"],
    "CARES": ["RACE", "CARS", "EARS", "ACE", "ARC", "SCAR", "ARCS", "ACRE", "ACES"],
    "GRINDS": ["GRINDS", "GRID", "RIND", "DING", "RING", "GRIN", "RINGS"],
    "PLANETS": ["PLAN", "PLANT", "LEAN", "PLATE", "STEAL", "LANE", "TALE", "PELT"],
    "CRANESD": ["DANCE", "SCARE", "RACED", "CEDAR", "CANE", "ACRE", "RAN"],
    "STORED": ["RODE", "DOER", "STORE", "DOTES", "TROD", "ODES", "SORE", "TORE"],
    "TRAINSE": ["STARE", "RETAIN", "SATIRE", "INSERT", "STAIN", "RAIN", "RISE", "TIRE"],
    "GRACE": ["RACE", "ACRE", "CAGE", "GEAR", "ACE", "ERA", "CAR", "AGE"],
    "DREAM": ["DAME", "MADE", "DEAR", "READ", "DARE", "MAE", "EAR", "RAM"],
    "BREAD": ["BRED", "READ", "DARE", "BARE", "DEAR", "EAR", "BED", "RED"],
    "FLAME": ["MEAL", "MALE", "MAE", "MEL"],
    "SOLID": ["SOLD", "DIS", "OLD", "DOS", "LID", "OIL", "LIS", "SOL"],
    "STONE": ["NOSE", "SENT", "NEST", "SON", "NET", "SET", "TEN", "NEO"],
    "WATER": ["WARE", "WEAR", "TEA", "ATE", "ARE", "RAT", "ERA", "TAR"],
    "OCEAN": ["CON", "ONE", "ACE", "NEO", "CAN"],
    "PEACE": ["CAP", "ACE", "PEE"],
    "SPACE": ["PACE", "CAPE", "SPEC", "ACE", "CAP", "PES", "ASP", "SPA"],
    "HEART": ["HART", "HEAR", "HEAT", "HATE", "HER", "ATE", "EAT", "ART"],
    "PLATE": ["LATE", "TALE", "EAT", "PAT", "LAP", "LAT", "LET", "APT"],
    "TRACK": ["RAT", "TAR", "ART", "CAT", "ARC", "ACT"],
    "SCALE": ["LACE", "SALE", "CAL", "SEA", "SEC", "LAS"],
    "PRINT": ["RIP", "PIN", "PIT", "TIP"],
    "CRAFT": ["TAR", "CAT", "CAR", "RAT", "ACT", "FAT", "FAR", "ARC"],
    "SMILE": ["SEMI", "ISLE", "LIME", "MEL", "LIS", "LIE", "MIL"],
    "FROST": ["FORT", "FOR"],
    "BRAVE": ["BAR", "ERA", "EAR", "BRA"],
    "QUIET": ["QUIT"],
    "PLATES": ["STEAL", "LATE", "TALE", "TAPS", "LAST", "SEAL", "SALT", "EATS"],
    "STREAM": ["TEAR", "RATE", "SEAT", "STAR", "EAST", "MESA", "STEM", "SAME"],
    "BRIGHT": ["BIRTH", "BIG", "BIT"],
    "FOREST": ["ROSE", "SORT", "REST", "FORT", "SOFT", "ERS", "SER", "REF"],
    "GARDEN": ["RANGE", "GRADE", "GRAND", "DEAR", "AGED", "READ", "DRAG", "NEAR"],
    "CASTLE": ["STEAL", "SCALE", "SALE", "SEAT", "EATS", "LATE", "CASE", "LAST"],
    "ISLAND": ["ISLAND", "LAID", "SAID", "DIAL", "SAIL", "SAD", "LID", "LAN"],
    "BRIDGE": ["BRIDE", "BIRD", "BRED", "RID", "DIE", "BED", "DIG", "BIG"],
    "DESERT": ["REST", "REED", "DEER", "SEED", "SET", "TEE", "ERS", "SEE"],
    "PLANET": ["PLANE", "PLATE", "PLAN", "LANE", "PALE", "TALE", "LEAN", "TAPE"],
    "WINTER": ["RENT", "TWIN", "TIRE", "WENT", "WIRE", "WINE", "WIT", "WIN"],
    "SPRING": ["RING", "SIGN", "SING", "RIP", "SIP", "PSI", "PIG", "SIN"],
    "SUMMER": ["USER", "USE", "SUR", "SUE", "SUM"],
    "MOTHER": ["HERO", "TERM", "HOME", "HOT", "TOE", "MET", "THE", "HER"],
    "FATHER": ["AFTER", "TEAR", "FEAR", "FARE", "RATE", "HEAR", "FATE", "HATE"],
    "TEACHER": ["HEART", "CHEAT", "CHART", "THERE", "EARTH", "TRACE", "TEACH", "CHAR"],
    "DOCTOR": ["DOOR", "COD", "TOO", "ROD", "DOC", "DOT"],
    "WONDER": ["WORD", "DREW", "DONE", "WORN", "END", "DOW", "ROW", "NEO"],
    "MARKET": ["TEAR", "MEAT", "RATE", "TREK", "MATE", "TEAM", "TAKE", "MART"],
    "BUTTER": ["TUB", "BET", "BUT"],
    "COTTAGE": ["GOAT", "GATE", "CAT", "TEA", "GEO", "EAT", "AGO", "TAG"],
    "TENDER": ["TREND", "NEED", "TEEN", "TREE", "RENT", "TEND", "REED", "TEE"],
    "MASTER": ["EATS", "STAR", "MESA", "MATE", "SAME", "TERM", "SEAT", "TEAM"],
    "POSTER": ["POET", "ROPE", "STEP", "SPOT", "REST", "POSE", "PEST", "STOP"],
    "TRAVEL": ["LATER", "EARL", "TEAR", "TALE", "RATE", "REAL", "ART", "ERA"],
    "MORNING": ["MIN", "NOR", "MON", "INN", "NON", "ION", "RIM"],
    "EVENING": ["GENE", "GIVE", "EVE", "INN"],
    "PICTURE": ["CURE", "CUTE", "RICE", "TRUE", "TIRE", "RIPE", "CITE", "EPIC"],
    "WEATHER": ["WHEAT", "EARTH", "THREE", "HEART", "WATER", "WERE", "HERE", "TEAR"],
    "JOURNEY": ["ONE", "OUR", "YOU", "RUN", "JOY", "NOR"],
    "MEETING": ["TEEN", "TING", "MINE", "TIME", "NET", "MEN", "TEE", "MET"],
    "READING": ["EARING", "GARDEN", "RANGED", "DARING", "ANGER", "RIDGE", "DRAIN", "GRAND"],
    "WALKING": ["AWING", "ALIGN", "LINK", "WING", "KING", "WALK", "LAWN", "WIN"],
    "FOREVER": ["FOREVER", "EVER", "OVER", "FREE", "FOR", "EVE", "REF"],
    "FREEDOM": ["MORE", "DEER", "DOME", "REED", "FROM", "FEED", "FREE", "FORM"],
    "STATION": ["SAN", "SIT", "NAT", "SIN", "ISO", "SAT", "ANT", "TON"],
    "VICTORY": ["IVORY", "CRY", "TOY", "TRY"],
    "MYSTERY": ["ERS", "YET", "YES", "SER", "TRY", "MET"],
    "HISTORY": ["SHORT", "SHOT", "HOST", "HIST", "SORT", "HIS", "ISO", "THY"],
    "FACTORY": ["FORTY", "COAT", "FORT", "CART", "FACT", "TRAY", "ARC", "FAT"],
    "GALLERY": ["RELAY", "LARGE", "RALLY", "EARLY", "EARL", "GEAR", "GREY", "RELY"],
    "STUDENT": ["USED", "TUNE", "STUD", "DUST", "SENT", "TENT", "SEND", "TEND"],
    "MANAGER": ["ARENA", "RANGE", "GAME", "GEAR", "AREA", "NEAR", "NAME", "MEAN"],
    "ARTISTS": ["TAR", "ITS", "ASS", "SAT", "ART", "SIS", "AIR", "SIT"],
    "PARTNER": ["TRAP", "EARN", "REAR", "RATE", "PART", "NEAR", "REP", "APT"],
    "MONSTER": ["MORES", "TONER", "STONE", "STORE", "SORT", "TONE", "MORE", "NOTE"],
    "PALACES": ["SPACE", "CAPES", "SALE", "PALE", "CASE", "PACE", "CAPE", "SPEC"],
    "TROPHY": ["TOY", "PRO", "TOP", "TRY", "POT", "OPT"],
    "STORIES": ["REST", "SORT", "RISE", "TRIO", "SITE", "ROSE", "SIR", "SIS"],
    "MOUNTAIN": ["MOUNT", "AMINO", "AUTO", "ATOM", "MAIN", "UNIT", "UNTO", "INTO"],
    "OBSERVER": ["BEES", "OVER", "EVER", "BEER", "OES", "ERS", "SER", "ROB"],
    "BIRTHDAY": ["DIRTY", "DIARY", "DAIRY", "YARD", "DIRT", "HAIR", "BIRD", "HART"],
    "ATTITUDE": ["IDEA", "DIET", "TUE", "AID", "ATE", "EAT", "TEA", "TIE"],
    "PARENTAL": ["LATER", "ARENA", "PLATE", "LEARN", "PLANT", "APART", "PLANE", "ALERT"],
    "STRENGTH": ["REST", "GENS", "RENT", "SENT", "TEST", "THE", "TEN", "ERS"],
    "TREASURE": ["EASE", "RARE", "RATE", "EAST", "TRUE", "USER", "SEAT", "TREE"],
    "STARTERS": ["STATE", "TASTE", "SEAT", "RARE", "RATE", "EATS", "TARS", "EAST"],
    "ELECTION": ["ELITE", "CLONE", "ELECT", "LONE", "TONE", "CENT", "INTO", "ICON"],
    "MAGAZINE": ["AGAIN", "MANGA", "GAME", "GAIN", "NAME", "MINE", "MEAN", "MAIN"],
    "INTERNET": ["ENTER", "TIER", "TREE", "TIRE", "NINE", "TENT", "TEEN", "TEE"],
    "EVERYDAY": ["VARY", "YARD", "DARE", "REED", "YEAR", "READ", "VERY", "EVER"],
    "DAUGHTER": ["GATED", "HEART", "GUARD", "EARTH", "DEATH", "RATED", "TRADE", "ARGUE"],
    "SOUTHERN": ["STORE", "HOUSE", "STONE", "THOSE", "TUNER", "ROUTE", "OUTER", "SHORT"],
    "DESIGNER": ["DESIRE", "SENDER", "SEEING", "DESIGN", "SINGER", "SINGED", "RINGED", "GREEN"],
    "ADVENTURE": ["ADVENTURE", "ADVERT", "AVENUE", "RENTED", "VANED", "VENUE", "ENTER", "NERVE"],
    "STATEMENT": ["STATE", "STEAM", "TENT", "EASE", "EATS", "TEST", "NEST", "STEM"],
    "BRIGHTEST": ["THEIR", "SHIRT", "TIGER", "TRIBE", "EIGHT", "BIRTH", "SIGHT", "HIRE"],
    "EVERGREEN": ["GREEN", "GENE", "EVEN", "EVE"],
    "WONDERFUL": ["FOLDER", "WONDER", "ROUND", "WORLD", "URLED", "OWNER", "RUNED", "WOULD"],
]
